### ISSUE TITLE
Song playing slightly too fast and pitch slightly too high

### ISSUE THREAD

**Issue by yannos1** [badaix/snapcast#102]
Hi,

I have installed snapserver 0.8 on an ubuntu 14.10 64 bits laptop, and snapclient 0.8 on both an android phone and a raspberrypi+Hifiberry Dac (using raspbian jessie light).
I have configured the server with the pulseaudio+pipe sink configuration explained in the readme.
In avoidance of doubt, my server config was:
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Radio&mode=read"
To play songs on my ubuntu laptop I both used a music player to play an mp3 and the spotify web player.

It worked really well on both my phone and raspberry pi. However, I soon realised that on both devices, songs played slightly too fast and with a slightly too high pitch (very hard to tell how much, my guess would be less than 5% difference). I can notice the difference when switching sink on my ubuntu laptop (snapcast fifo and built-in sound card), and I am pretty sure that the built-in sound card plays at the right speed/pitch. I also borrowed someone else's ears and they agreed with my observation.
I tried to change the sampling rate in SNAPSERVER_OPTS to 44100, but it did not change anything. I tried to change the codec to pcm, but no luck either. I observed same results playing a local mp3 file on my ubuntu laptop or streaming the same song from the spotify web player.

Any idea of what is going on?

Cheers

**Comment by badaix** [comment]
this in fact sounds like you're feeding 44.1kHz audio while the server is expecting 48kHz.
What it your input signal?

Did you change the server options to this?
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Radio&mode=read&sampleformat=44100:16:2"`

You can also stop the service and start the server on command line to play around with the parameters

**Comment by axelsimon** [comment]
I just ran into that problem and indeed, telling snapserver to expect 44.1 KHz works a lot better.
I'm wondering if it wouldn't be better to tell snapserver to expect 44.1 by default, AFAIK, most music is in 44.1 and mostly films are in 48 KHz (DVDs) and most people will want to sync music in their homes, not film soundtracks.
It also raises two questions, what happens if you read high-def audio (96 or 128 KHz and 24 bits) and how can snapserver better deal with various sample rates, as people might throw different things at it. I'm especially considering this with the idea of combining Kodi with snapcast, which could provide really great multiroom but not if one has to change the `sampleformat` option on every sample rate change ;)

**Comment by yannos1** [comment]
Hi badaix. Yes, I thought I did change SNAPSERVER_OPTS to what you suggested as I had the same suspicion as you, but I must have done something wrong somewhere when I did it since after having paranoidly gone through the steps again, the song plays at the right speed/pitch.
So I consider this issue fixed now, thanks a lot.

**Comment by palitu** [comment]
yep - this fixed it for me.

**Comment by someinternetguy** [comment]
Thanks so much for posting this, I had the same issue with the default settings playing every so slightly too fast using Spotify connect on volumio thru snapcast... Changing to 44.1kHz worked like a charm!!
