### ISSUE TITLE
Can't compile on macOS 10.15 Silicon

### ISSUE THREAD

**Issue by Drun555** [badaix/snapcast#1028]
Firstly, there was a error in utils.hpp

`note: 'kIOMasterPortDefault' has been explicitly marked deprecated here`

because kIOMasterPortDefault was renamed to kIOMainPortDefault. If you manually change this, the build continues, but only to crash later at 9% with 6 errors. Mostly there's boost-related deprecation errors.

**Steps to Reproduce**
1. Try to compile with instructions from README.md
2. Fail, then try to compile with instructions from here: https://github.com/badaix/snapcast/issues/896
3. Deprecation issues everywhere

**Environment details**
- OS: macOS 10.15
- Latest snapcast, main/delevop branch
- Self compiled

**Attach logfile if applicable**
[cmake_log.txt](https://github.com/badaix/snapcast/files/9017466/cmake_log.txt)

**Comment by badaix** [comment]
Which xcode version do you use?

If someone has unused Mac hardware: I'm accepting donations, please send it to my private address ;)

**Comment by badaix** [comment]
Xcode 13.4.1 seems to work (see this [run](https://github.com/badaix/snapcast/runs/7129677000?check_suite_focus=true)). I guess that you did not add the CXX flag `-DCMAKE_CXX_FLAGS="... -Wno-deprecated-declarations"`. You could also remove this option: `-DWERROR=ON`.
Please note that nothing is crashing, only the compilation stops because of the deprecation warning, in combination with the setting that warnings should be handled as errors.

**Comment by badaix** [comment]
The develop branch should now work without the `-Wno-deprecated-declarations` flag: c77040ee1ebc8ef276d11bcff3837690e4d1c04a

**Comment by Drun555** [comment]
Thank you for fast response!

Thank you for your commit! I still got issue below
```
[  9%] Linking CXX executable ../../bin/snapserver
ld: library not found for -lsoxr
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So I did `export LIBRARY_PATH="$LIBRARY_PATH":/opt/homebrew/Cellar/libsoxr/0.1.3/lib/` and it worked!

Thanks for this project, it's just fantastic piece of work. Multiroom + LedFX finally working!
