### ISSUE TITLE
Slow playback and seek issue

### ISSUE THREAD

**Issue by timt-unity3d** [badaix/snapcast#11]
So I'm having two issues. I started playing with this with mopidy. Your instructions work great for Spotify and web streaming, but when I try to play local mp3 files they play back at about half speed.

I'm also having an issue with mopidy where it won't advance to the next track because it tries to do a seek at the end of the file that fails. Probably a mopidy bug, but I wanted to put it out there in case there's a known seek issue.

Any clue on where to start troubleshooting these issues. Otherwise the clients work wonderfully. I've been adding a small webserver using libevent to allow changing the server a client is pointed at and will hopefully be building a front end for that as well.

**Comment by badaix** [comment]
Hi,

maybe the resampling has to be parameterized? E.g. with something like that: "audioresample ! 'audio/x-raw-int, 
rate=48000'". I'm not aware of the exact syntax and the available options (and I don't have my computer available (due to vacation :grinning:)). But I bet it's related to different sample rates, like playing 96kHz at 48kHz.

**Comment by tthomas48** [comment]
Thanks! That did work... but then broke Spotify playback. What fixed the slow playback was installing the fluendo mp3 plugin rather than the mad one. Install gstreamer0.10-fluendo-mp3. 

The not advancing is a known mopidy bug with streams (check out the docs on configuring icecast servers). It has been fixed in 1.2 and I'm using the dev branch right now to solve it. You can install that with:

sudo pip install --upgrade --allow-unverified=mopidy mopidy==dev

Hope these tips are helpful for others.

**Comment by buzink** [comment]
Hi Tim, any chance you could share the web server source code with us?

>I've been adding a small webserver using libevent to allow changing the server a client is pointed at and will hopefully be building a front end for that as well.

**Comment by timt-unity3d** [comment]
Absolutely. Realized I commented with work rather than personal github which is why you can't find my fork.. It's here:

https://github.com/tthomas48/snapcast

I've since had to abandon my work on this project due to lack of time (and issues with mopidy), but hopefully some of the web stuff will be useful as a starting point for others.

**Comment by buzink** [comment]
Thanks!
