### ISSUE TITLE
Snapserver considers two independent devices as 1

### ISSUE THREAD

**Issue by iamhai** [badaix/snapcast#1159]
**Describe the bug**
I have a snapserver running on armbian and 2 android clients (pixel 4 and pixel 6) connecting to it. But the server considers these two independent devices as 1. When I connect client pixel 4 to the server, client pixel 6 immediately switches to pixel 4. Then when I connect pixel 6 to the server, the connected pixel 4 device switches again to pixel 6. The client list only shows 1 device name.

**Steps to Reproduce**
1. Reset
2. Install snapserver on fresh system
3. Same problem

**Environment details**
OS: Linux armbian 6.1.52-ophub #1 SMP Thu Sep  7 03:11:29 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux
Snapcast version 0.27.0

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
Sep 21 14:19:12 armbian snapserver[1417]: StreamServer::NewConnection: 192.168.1.101
Sep 21 14:19:12 armbian snapserver[1417]: Hello from b54aa6fd-1d3a-467b-922b-c1e6c8175f8c, host: Pixel 6a, v0.27.0, ClientName: Snapclient, OS: Android 13, Arch: arm64-v8a, Protocol version: 2

Sep 21 14:19:22 armbian snapserver[1417]: StreamServer::NewConnection: 192.168.1.7
Sep 21 14:19:22 armbian snapserver[1417]: Hello from b54aa6fd-1d3a-467b-922b-c1e6c8175f8c, host: Pixel 4, v0.27.0, ClientName: Snapclient, OS: Android 13, Arch: arm64-v8a, Protocol version: 2
```

**Comment by kerta1n** [comment]
Try using the `--instance` flag

**Comment by badaix** [comment]
What client are you using on the Android devices? Snapweb? Snapdroid?
Every client is expected to identify itself with a unique ID towards the server. Snapclient is usually using the MAC address, but the MAC address of the host cannot be queried on Android, nor from a web client, so they are both creating a uuid on their first start and persist it for future use. You can see the unique client ID's in the client details in Snapweb and Snapdroid (the three dots button next to the client).
 I guess that you synced your apps and data from the Pixel 4 to the Pixel 6, which will also sync the app-data, and so the Pixel 6 will appear as the same device. You can simply delete the app data for Snapdroid on the Pixel 6, so that Snapdroid will create a new UUID during the next start.
