### ISSUE TITLE
Change dependencies

### ISSUE THREAD

**Issue by mathisloge** [badaix/snapcast#1191]
**Is your feature request related to a problem? Please describe.**

I think it might make sense to switch to some other dependencies, which might be more maintained. I don't want to be rude here or something else, but snapcast depends on aixlog and popl which haven't seen any commits since 3 years now. 

I would take the work on me to change the deps as follows: 

* Introduce https://github.com/fmtlib/fmt for all string formatting. to_string especially for floats and double it is quite slow and inaccurate.
* aixlog -> spdlog (only dependency is fmt) (especially good to have the different log sinks, systemd-journal, android, etc.)
* popl -> CLI11 (can parse ini and toml config files, so the config format won't have to change)

Those are all really common and high quality libraries and available on the typical systems: 

* fmt https://packages.ubuntu.com/search?keywords=libfmt-dev
* spdlog https://packages.ubuntu.com/search?keywords=spdlog
* cli11 https://packages.ubuntu.com/search?keywords=libcli11 (could also be used as a single header file)

I hope to get more familar with the source code with this work to contribute more in the future, since it works really great already for me at home.

**Comment by StefanBruens** [comment]
Instead of libfmt, just using C++20 (std::fmt) may be the simpler option. Current spdlog supports std::fmt instead of libfmt.

**Comment by badaix** [comment]
I think it's always a good idea to use existing, mature libraries instead of reinventing the wheel, but when I started with Snapcast I didn't find any simple logger, nor I found any simple command line parser, that was supporting Linux, Windows, MacOS and Android. Especially for Android it's desirable to have a header only libs.
Popl has also the advantage that it can be fet from command line as well as from an ini file. Both libraries didn't cause a single issue in the last ten years of Snapcast, so I prefer sticking to them.
Btw: there is a branch of aixlog that supports std::fmt.
