### ISSUE TITLE
[Feature Request] Snapclient: Free Alsa when muted

### ISSUE THREAD

**Issue by unimatrix27** [badaix/snapcast#150]
It would be great if the snapclient could release the sound device when its muted. On top of that I guess also the transmission of data could be suspended. This way I could keep a snapclient running on my KODI box and not have it block the sound device when I mute it. I can also trigger a mute of the client via a KODI plugin so that KODI mutes the client just before KODI starts to output sound itself and unmutes it possibly afterwards. For that to work it would be required that the device is freed asap after muting, not after a few seconds.

**Comment by ismailof** [comment]
I have a Raspberry running Kodi (xbian distro) and snapclient and they can
share the alsa audio output with no problem.

But still the possibility to stop the audio stream to some clients would be
great. In my case mainly to avoid the extra network traffic and maybe the
server unnecessary load.

El lun., 12 dic. 2016 19:02, unimatrix27 <notifications@github.com>
escribió:

It would be great if the snapclient could release the sound device when its
muted. On top of that I guess also the transmission of data could be
suspended. This way I could keep a snapclient running on my KODI box and
not have it block the sound device when I mute it. I can also trigger a
mute of the client via a KODI plugin so that KODI mutes the client just
before KODI starts to output sound itself and unmutes it possibly
afterwards. For that to work it would be required that the device is freed
asap after muting, not after a few seconds.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/badaix/snapcast/issues/150>, or mute the thread

**Comment by unimatrix27** [comment]
sharing works with KODI, but KODI cannot change 2 channel output to 6 channel output vice versa as long as snapclient blocks the hw.

**Comment by unimatrix27** [comment]
I did a quick hack on the snapcast client, which frees the alsa device whenever the client is muted. The hack does not stop the transmission of data, it is only a client change. It might have side effects and is not well tested.

https://github.com/unimatrix27/snapcast/commit/88e42a2ecc8b44223701e18abb63af04b673b67b

**Comment by apirogov** [comment]
I wanted to open a feature request to stop sending data to muted clients, as this is mentioned here, I just want to say that I also really want this.

I use a RPi 1 with MPD with up to 3-4 clients, but not all of them are used all the time, but I'd like to keep snapclient running and just mute/unmute. I think the RPi can't keep up sending the FLAC stream to >2 devices without stuttering, so I would mute the ones I don't use and expect that no audio is sent there, but right now I really have to kill the clients to prevent the useless wasting of bandwidth..

**Comment by badaix** [comment]
With commit 39c133e4 the server will not send audio to muted clients, causing ALSA to close after the 5s w/o a signal timeout.
The old behavior can be switched on with the `--sendToMuted` flag.

This will be part of the 0.11.0 version.
