### ISSUE TITLE
Snapcast android client on i686

### ISSUE THREAD

**Issue by ulno** [badaix/snapcast#178]
I am trying to build the android client for i686 devices (i.e. Asus Zenfone 2).
The documentation regarding the android client is a little brief.
Building flac and ogg was easy. I skipped tremor and enabled ogg in flac. Popl seemed to also have been required, so building this is also easy. However Asio requires boost and before I start going down to the dependency hell, I was wondering if there is any shortcut? Is there any ready made boost-android-i686 library, which can or should be re-used?

**Comment by badaix** [comment]
Asio doesn't need boost, because it's compiled with `ASIO_STANDALONE`.
I updated my Android tool chain to version r13b at the weekend by following the [build.md](https://github.com/badaix/snapcast/blob/develop/doc/build.md). The documentation is brief, but complete (at least I could successfully build for ARM, X64 should be similar).
The only libs that have to be built are `FLAC`, `ogg` and `tremor`, which is done by the [build script](https://github.com/badaix/snapcast/blob/master/externals/build_externals_android.sh).
Regarding `Asio` and `popl`: both are head only and don't need to be build as library.
