### ISSUE TITLE
changing Audio output

### ISSUE THREAD

**Issue by mattpitts74** [badaix/snapcast#19]
Hi There, 

I have installed snapcast to stream audio between two raspberry pies the server is running snapcast and mpd, but I would like to be able to route the audio in the client back through my DAC, is that possible? because it only seems to play through the 3.5mm jack.

**Comment by badaix** [comment]
You can choose the soundcard with the `-s` or `--soundcard` parameter. You can either configure the index or a substring of the name of the soundcard.
In my setup I have for example one raspberry with a Behringer UCA202 and on another raspberry I have a HifiBerry DAC+ connected.
You can list the soundcards with `snapclient -l`. The Behringer system gives:
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: default:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

2: sysdefault:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

3: default:CARD=CODEC
USB Audio CODEC, USB Audio
Default Audio Device

4: sysdefault:CARD=CODEC
USB Audio CODEC, USB Audio
Default Audio Device
...
```
Device #4 is the Behringer DAC. So I have added `-s 4` in the service file (`/lib/systemd/system/snapclient.service`):
```
[Unit]
Description=Snapcast client
After=network.target

[Service]
Type=forking
ExecStart=/usr/sbin/snapclient -d -s 4
PIDFile=/var/run/snapclient.pid

[Install]
WantedBy=multi-user.target
```

The raspberry with the HifiBerry is working out of the box ([using this setup](https://www.hifiberry.com/guides/configuring-linux-3-18-x/)), because the devices are as follows:
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: sysdefault:CARD=sndrpihifiberry
snd_rpi_hifiberry_dacplus, 
Default Audio Device

2: dmix:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus, 
Direct sample mixing device
```
snapclient will use device #1, because `default` is a substring of `sysdefault`
