### ISSUE TITLE
Question about API - making server send updates.

### ISSUE THREAD

**Issue by noaht8um** [badaix/snapcast#190]
Hello,

I have been writing a node.js API for snapcast and I can't seem to figure out the mechanism for "registering" with the server so it sends updates. I've studied the Android code, but I can't seem to pull any answers out.

I listen on port 1705 on my snapcast server, and everytime I change some setting with my API, I see the server tell the Android client about it, and it updates almost instantaneously (good work with that by the way). On my desktop that I've been sending the server commands, I also have netcat running in listen mode on port 1705, but it never gets information. What does the process look like to tell the server to send my client updates? I don't want it to stream the audio, just get updates on status. Even if you could push me in the right direction or refer to a particular Android code file, I'd be much obliged.

My goal with this API is to build a web interface on top so it can work as a standalone controller for snapcast. Once I make some real progress, I can put in on GitHub. I'm also still trying to force myself to remember to do things asynchronously with Node ;)

Thanks!

**Comment by happyleavesaoc** [comment]
You should get updates merely by opening the connection. Note that you won't get updates resulting from commands YOU send. Only what other clients do.

Take a look at my Python API: https://github.com/happyleavesaoc/python-snapcast

**Comment by unimatrix27** [comment]
netcat in listen mode is not going to help you. Snapcast does not actively open a connection. Your app needs to open a connection to the SC server on port 1705 and keep this connection open. The server will inform through this connection about any updates made by other clients. For your own updates, your app needs to remember what command with which IDs it has sent and Snapcast will give you a result JSON back refering to this ID, so that your app knows, that the command was processed successfully (or not).

**Comment by badaix** [comment]
there is still no exhaustive documentation of the API, but [this](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md) might help you.
All types of messages (requests and notifications) are listed and, for the first start, the hint to simply use a telnet connection to see incoming notifications and to send some simple requests interactively.
Please all of you note that the API has changed in 0.11.0-beta-1 due to the introduction of "Groups". This is one reason for being "beta"

**Comment by badaix** [comment]
Ok to close this?

**Comment by 1337sup3rh4x0r** [comment]
Is the 0.11 API backwards compatible to 0.10?
E.g. will scripts that I currently use to send commands to the 0.10 snapserver still work after upgrading to 0.11?

**Comment by airdrummingfool** [comment]
@1337sup3rh4x0r no, your scripts will need to be changed. The big differences that I have encountered are:
* the introduction of groups
* `Client.SetVolume` expects volume object instead of int
* `client` in params has been renamed to `id`

**Comment by badaix** [comment]
...and it's still beta, meaning the API is not considered stable. Just in case that you have some ideas to improve. 
I tried to make it more consistent. For example is not only `client` but are all objects referenced by their `id` (`client`, `group`, `stream`)
