### ISSUE TITLE
Setup Instructions with RuneAudio

### ISSUE THREAD

**Issue by ringzer** [badaix/snapcast#20]
Hi,

I'm trying to get SnapCast running with RuneAudio so I can have music in two rooms running on 2 different Raspberry Pi's.

I found this thread: http://www.runeaudio.com/forum/rune-transmitter-t210.html and have tried to compile a high level list of steps by reading the Snapcast instructions to see how I can set it up.

However as per my post there http://www.runeaudio.com/forum/rune-transmitter-t210.html#p10931 I've come up short on the last few steps to get the music to play on the master instance of RuneAudio and the slave which is running the Snapcast client.

I found this link for Volumio which is very similar to RuneAudio
https://volumio.org/forum/multiroom-audio-output-from-volumio-with-snapcast-t3217.html

Are you able to comment either here on the RuneAudio forum as to what the missing steps are?

Thanks in advance.

Ciaran

**Comment by badaix** [comment]
Generally, only the Snapclient will play audio. This means you have to install a Snapclient also on RPI #1, so that it can connect on localhost to the Snapserver. 
You could configure the IP address of the server, but the client will find the server automatically, because the server broadcasts the host name, port and ip address via Avahi ZeroConf.
The easiest way to setup a snapclient is the "Install debain package" option (https://github.com/badaix/snapcast#install-debian-packages). 
Actually, the quickest way is to install the Snapclient on Android. An early prototype can be found here: https://github.com/badaix/snapcast/files/77482/Snapcast-0_4_9_alpha.apk.zip (see: https://github.com/badaix/snapcast/issues/9)

**Comment by ringzer** [comment]
badaix,

Thanks for the update. I'm posting on here rather than the RuneAudio forum as I ended up installing Volumio on RPi #1 along with SnapCast server and client. On RPi #2 I installed Raspian and installed SnapCast client. I built SnapCast manually on both Pi's and only realised afterwards I could have just installed the package.

However before that, I had tried building SnapCast on RPi #1 which had Rune Audio installed. However I was getting some build errors and couldn't fix them. And as it is based on Arch Linux, I couldn't install the Debian package.

Can you upload a Arch Linux package so people can install directly alongside Rune Audio?

Having got it working now, can you comment on what the likely cause is for either gaps in play, or delay in either client outputting music even though something is playing? Are the gaps due to WiFi dropping? Is there any config setting which I could tweak to improve the performance? Can I increase the buffer to the output file or similar?

Thank you for an awesome piece of software. It should definitely be integrated into more Volumio/RuneAudio apps. My wife is very impressed at our multi room audio!

Thanks

Ciaran
