### ISSUE TITLE
snapserver 0.11.0 requires recent version of librespot

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapcast#217]
And it's hard to compile librespot for a rpi2, right now 😃

Up until recently, @badaix maintained a librespot repo with builds of librespot ready to be used (worked and works great with `snapcast 0.10.0`). I updated to `snapserver 0.11.0`, and quickly it appeared that with or without username and password (ie: in discovery mode or not), that version librespot wasn't doing what it should.

I tried building librespot following instructions (using a docker container to crosscompile for `armhf`) but the docker container ends in errors.
So currently, unless I'm missing something, if one updates form 0.10.0 to 0.11.0, one also has to update librespot, which is tricky, currently.

**Comment by airdrummingfool** [comment]
You should be able to continue using your existing build of the forked `librespot` with 0.11.0. Since the repo is gone I can't double-check, but if memory serves it output to `stdout` if you used the `stdout` backend. If that is the case, you can use the ["process" snapserver config](https://github.com/badaix/snapcast/blob/develop/doc/player_setup.md#process) (instead of the "spotify" config). e.g.:

```
snapserver -s "process:///librespot?name=LibreSpot&params=--cache /tmp/librespotcache --backend stdout --name LibreSpot&logStderr=true&sampleformat=44100:16:2"
```
