### ISSUE TITLE
Auto Update client

### ISSUE THREAD

**Issue by palitu** [badaix/snapcast#220]
I will be having numerous clients installed on headless Pi Zero W's, and as a result i would hate to have to go and manually update them to the latest version every release.

Is it possible to allow the server to push updates out?  so if you update the server to v0.12, it will push the v0.12 client out to all connected clients (and the app if possible)? This could be enabled/disabled on the server, or pushed out via the android client.

I found that there were issues when updating the server and not the client or android app, and it was a bit of a pain going through and individually updating them all

cheers,

Palitu

**Comment by badaix** [comment]
I'm afraid that this is not really feasible, because there are too many different architectures within the the same Snapcast network.
A better approach would be to use the update mechanism of the OS. This means: Google play store for the App (there is/was already a Snapcast version in the [F-Droid store](https://f-droid.org/wiki/page/de.badaix.snapcast)), a PPA for Debian, ...
Other approaches:
1. Trying not to break compatibility (I changed for example the Control protocol from v0.10 to v0.11)
2. Try to be backward compatible or at least show in the Android App a meaningful error message

**Comment by palitu** [comment]
Fair enough.

cheers,
