### ISSUE TITLE
Crack/click/pop sound when changing track with Mopdiy/fifo

### ISSUE THREAD

**Issue by JonesN7** [badaix/snapcast#222]
I have a snapcast setup with librespot and mopdiy. 

Mopidy is configured with 
`output = audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo`

When changing tracks with Mopidy, I get a quite loud crackling/clicking sound. This is noticeable when i use a snapclient on my laptop, and with the snapclient running on my server through a minijack to an amplifier, and snapclient on my android phone.  The librespot pipe works perfectly.

**Comment by FilipLigaarden** [comment]
Can confirm, i have experienced this myself.

**Comment by badaix** [comment]
Might it be related to the gstreamer version, as discussed in #17?

**Comment by badaix** [comment]
any news?
what happens if you feed aplay with the fifo?

**Comment by freedreamer82** [comment]
same here , two raspberry mopidy with fifo and a very loud pop every time I change track. any soulution ?
thanks!

**Comment by freedreamer82** [comment]
compiled gstreamer on raspeberry with last version. Problem seems gone , i guess it's not related to snapcast.

**Comment by gerroon** [comment]
HI 

I seem to have the same issue with Mopidy 2.1.0 on Debian Testing.

I do not want to compile gstreamer myself if possible, since I like to keep my Debian close to original distro.

I tried these lines

```
output = audioresample ! audioconvert ! audio/x-raw,rate=44100,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo
 
output = audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo

```

**Comment by groldo** [comment]
As I was coming to this issue with the exact same problem and there wasn't any guideline to follow how to get this fixed,
I will give a quick overview of how I eventually got this fixed.

Like already stated it isn't a problem with snapcast.
And by the way thank you @badaix for this great piece of software.
While this isn't a snapcast issue it is linked to it closely.

I have a Docker setup with mopidy and snapcast with two container collaborating.
The mopidy one is supposed to do the music generating magic and pipe it to the snapcast server container and then does its snapcast voodoo.

To get this fixed I installed alsa inside the mopidy container

```bash
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libasound2 \
        alsa-utils \
        alsa-oss
```

and also added a asound.conf like [this](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#alsa)
inside the container.

And then just change the output in mopidy from 
```
output = audioresample ! audio/x-raw,rate=44100,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo
```
to
```
output = autoaudiosink
```

After this the cracking sound disappeared.
But then the audio output on the snapcast clients was pretty "slow". 
So I changed

```
output = autoaudiosink
```
to
```
output = alsasink
```
which fixed the slow audio out.

Hope some of the poor souls out there might help this.

I first tried to get pulseaudio going inside the mopidy container to pipe the output to snapcast.
But pulseaudio seems to be to heavily linked to dbus.
So I canceled this. Save yourself some work and just skip this idea.

**Comment by kingosticks** [comment]
Where did you get that odd Mopidy output config from?

**Comment by groldo** [comment]
Do you mean this line:
```
output = audioresample ! audio/x-raw,rate=44100,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo
```
Actually I can't remember. It have been quite some time since I made the config for mopidy.
My first thought was, that it was coming from [here](https://github.com/badaix/snapcast/blob/1f98c790734f7b5de01497fa5243149dddd6dc0b/doc/player_setup.md#mopidy).
But its slightly different.

**Comment by kingosticks** [comment]
Yes, that line. 

That is the danger of using third-party guides; they are usually outdated and often full of junk. Reviving *really* old posts isn't usually helpful but since we are here it's worth tracking down the source of the incorrect information. I will ask them to update or remove. It's not much of a surprise that using config from an article in 2016 doesn't work today.

The config in the [snapcast docs](https://github.com/badaix/snapcast/blob/1f98c790734f7b5de01497fa5243149dddd6dc0b/doc/player_setup.md#mopidy) is indeed slightly different, in ways that mean it works with current software.

**Comment by groldo** [comment]
Thank you, i did give it a try with this
```
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo
```
and it now works like charm without my alsa workaround.

**Comment by fredele** [comment]
I can confirm groldo's saying.

With the line:
`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo`
the problem is GONE !

It' also the case if you send the sound to ALSA.

Another solution if using Pulseaudio  : let mopidy play to pulse audio and set a pipe-sink in pulseaudio to the snapserver FIFO.
This can be done if you add at the end of  the file `etc/pulse/default.pa` this two lines :
`load-module module-pipe-sink file=/tmp/snapfifo sink_name=SnapcastServer format=s16le rate=48000
update-sink-proplist SnapcastServer device.description=SnapcastServer`

**Comment by kingosticks** [comment]
Yes, avoiding gstreamer filesink is a good plan. The following other methods are also now available:
* https://github.com/badaix/snapcast/blob/master/doc/configuration.md#tcp-server
* https://github.com/badaix/snapcast/blob/master/doc/configuration.md#tcp-client
* https://github.com/badaix/snapcast/blob/master/doc/configuration.md#alsa

**Comment by VDRainer** [comment]
Sorry for posting in this old issue.
I also had this problem and removing `wavenc` from the output line in mopidy.conf fixed it for me.
```
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! tcpclientsink host=<IP> port=4953
```
Can someone explain what it was good for, or if there are any downsides, removing it?
Most of the examples i found in the net, include it.
Thanks in advance!

**Comment by kingosticks** [comment]
From https://gstreamer.freedesktop.org/documentation/wavenc/index.html 
> Format an audio stream into the wav format.

The wav format has a header and then PCM data. So I am guessing GStreamer is putting a new header on for each track change and snapserver is treating that as audio data. There should be no need for a wav header so it should be fine to get rid of it.

I think this must just be a mistake in the documentation at https://github.com/badaix/snapcast/blob/master/doc/configuration.md. Is that right @badaix ?
