### ISSUE TITLE
Look for user config, honour XDG directories

### ISSUE THREAD

**Issue by seanrand** [badaix/snapcast#231]
Currently, when compiling and running snapserver(/-client) without installing it through a package manager, the options defined in /etc/defaults/snapserver(/-client) don't seem to be honoured. Maybe looking for or creating a .config/snapserver/server.conf (or similarly-named) file would be an idea.

Also, why use /etc/defaults/ and not implement the [XDG Base Dir Specs](https://standards.freedesktop.org/basedir-spec/latest/ar01s03.html) right away (with fallback to /etc/xdg/)?

I'll try to find the time to create a PR, but can't promise anything.

**Comment by airdrummingfool** [comment]
The snapserver executable doesn't actually reference any config files (such as `/etc/defaults/snapserver`) for defining streams, etc.

The config files in `/etc/defaults/` are used by some of the helper scripts that are installed by the Makefile on certain platforms. It looks like only `systemd`, `sysv`, and `bsd` installations have the option to configure defaults in a file.

For example, the file `snapserver.init` (installed to`/etc/init.d/`) sources `/etc/default/snapserver` and then passes the result straight to the snapserver binary as command line arguments.

It would be great for snapserver/snapclient to have a config file that it referenced on start, instead of having to pass all options via command line arguments. Perhaps that config file could be some default location, but changeable via argument (e.g. `/usr/bin/snapserver -C /my/config/file.conf`).

**Comment by HazWard** [comment]
@seanrand Unfortunately this issue is still present, my temporary _fix_ for this is to wrap the ``snapserver`` command inside a bash script where I define the parameters I want to use. Like @airdrummingfool said the files located in ``/etc/default`` are only used for the start up scripts in ``systemd`` or ``sysv``.

**Comment by badaix** [comment]
There is a `-c`, `--config` option for a while now
