### ISSUE TITLE
client plays too fast then waits.

### ISSUE THREAD

**Issue by dksayers** [badaix/snapcast#244]
Have installed a hifiberry DAC+ onto a Raspberry Pi 2 to sync music using snapcast. If I use mpg123 file.mp3 directly on the pi, playback is fine. I then played the same file on my PC set up as the snapcast server:

$ mpg123 -s "file.mp3" > /tmp/snapfifo
Playing MPEG stream 1 of 1: file.mp3 ...
MPEG 1.0 layer III, 192 kbit/s, 44100 Hz joint-stereo

The music plays but its sounds slightly too fast (beat is quicker) and has a higher pitch, then regularly will go silent and continue again. Most annoying....

I have set the snapserver config to:

SNAPSERVER_OPTS="-d pipe:///tmp/snapfifo?name=MPD&sampleformat=44100:16:2"

The client has a default config:

SNAPCLIENT_OPTS=""

Using the suggested test will also produce a sub second silent period every 5/10 seconds
$ cat /dev/urandom > /tmp/snapfifo

**Comment by zeekoe** [comment]
I have the same behaviour on the Android client; Ubuntu client is okay. Have to dive into it a bit more...
Because all of my music is from CD, I also have 44100. But with a slightly different config:
`SNAPSERVER_OPTS="-d --sampleformat 44100:16:2 -b 200"`
In /etc/default/snapserver it says this:
`#   -f, --fifo arg (=/tmp/snapfifo)     name of the input fifo file`
Perhaps that helps?

**Comment by dksayers** [comment]
Thanks for the hints. I changed the options and I believe the -b helped. I still have dropout/skipping and cant find the sweat spot yet but will investigate more.
