### ISSUE TITLE
No settings file - is there an example?

### ISSUE THREAD

**Issue by Br3nda** [badaix/snapcast#247]
Sorry if this is documented but i've searched most of today and can't find it.

I've installed snapserver on my ubuntu server, compiling from git (because there's no i686 deb in releases).

when i start snap server i get this
```
brenda@kokako:~$ snapserver
Settings file: /home/brenda/.config/snapserver/server.json
2017-06-05 17-51-19 [out] Adding service 'Snapcast'
2017-06-05 17-51-19 [Notice] StreamServer::start: bind: Address already in use
2017-06-05 17-51-19 [Err] Exception: bind: Address already in use
2017-06-05 17-51-19 [Notice] daemon terminated.
```

` /home/brenda/.config/snapserver/server.json` does not exist.

Questions:
- Is there an example somewhere of what should go in settings?
- What tcp port is it trying to use by default?

**Comment by badaix** [comment]
This is not a public settings file, but rather a file where the server persistently stores it's state (client volumes, etc).
Your server does not come to the point where he would write into the config file, since the address is already in use (is there another instance running?).
BTW: the amd64.deb is the proper one for you. This is the official name for 64bit deb's. I think because AMD first introduced the 64bit architecture.

**Comment by Br3nda** [comment]
amd64 seems wrong. This is a 32bit device. Not 64.

**Comment by coda4k** [comment]
Excuse me @badaix, where is that config file located? Every time I restart my snapcast server, all volumes reset to 100% and then I have to set each client to it's stream again. Thanks in advance!

**Comment by ThYpHo0n** [comment]
@coda4k /var/lib/snapcast/server.json is it for me (stared as a systemd service). But you shoudln't even consider changing values in there by hand but instead use the Json-RPC API.

**Comment by coda4k** [comment]
Thank you very much @ThYpHo0n! The problem was that /var/lib/snapserver was owned by root and I'm running the daemon as 'snapserver' user. Changing it's owner/group to 'snapserver' fixed the problem!
