### ISSUE TITLE
android client list blank?

### ISSUE THREAD

**Issue by stanelie** [badaix/snapcast#259]
Hello.

I just upgraded my old 0.7 android client that was crashing on my recently upgraded phone (Nougat) to the latest v0.11.1. 

However, now, my client list is just blank, even after clicking "refresh client list" in the menu.

Thanks!

**Comment by stanelie** [comment]
I just re-downloaded all the builds since version 0.7, the last version that allows me to see the snapclients is version 10. Starging with beta 11, I lose this feature.

**Comment by cortegedusage** [comment]
There was some change between 0.10 and 0.11 which makes them incompatible,
I cannot find the source right now.

Op 20 jul. 2017 6:46 p.m. schreef "stanelie" <notifications@github.com>:

I just re-downloaded all the builds since version 0.7, the last version
that allows me to see the snapclients is version 10. Starging with beta 11,
I lose this feature.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/badaix/snapcast/issues/259#issuecomment-316763170>, or mute
the thread

**Comment by badaix** [comment]
you have to update your server and clients as well, as the control API changed from 0.10 to 0.11 (unfortunately without explicit notice)
