### ISSUE TITLE
Play from mobile

### ISSUE THREAD

**Issue by arjunmenon** [badaix/snapcast#287]
I just discovered Snapcast from a mention here in the comments - https://www.lesbonscomptes.com/pages/homenet-audio.html

In Upnp, I can set the `SetAVTransportURI` to a music file in my mobile or even to a external media file and give the `Play` command.

So basically this allows development of a music player for mobile with Upnp support.

What is the equivalent of it in Sgnapcast? I checked here - https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md - but it was not clear to me? Is it the `Stream`?

**Comment by badaix** [comment]
Snapcast is really passive. You must actively feed audio into one of the server's Streams (e.g. named pipe).
I have a Snapcast server running on a Raspberry pi, along with MPD. MPD's output is the Snapcast's input pipe, and MPD is also acting as UPnP receiver. 
An Android phone can act as an UPnP controller, telling the MPD server on the Raspberry to play some song. The song is rendered into the Snapserver pipe and distributed to all connected Snapclients.
Does this answer your question?

**Comment by arjunmenon** [comment]
Not exactly.
If I have to develop an ecosystem, this is what it would be like? - 
1. There needs to be snapcast running on Pi.
2. There also needs to be MPD running on Pi.
3. To control them, you need a upnp control point on your mobile.
4. To play local music, you need a Upnp server on your mobile.

Mostly I am interested in the controlling part. If step `1` is interchanged with Upnp server on Pi or OpenHome or even Songcast, controlling them sucks!
It becomes difficult to manage all services on mobile and sync them all to behave correctly. I have already tried with Upnp and somewhat with Openhome. I had some very late nights.

With snapcast is there any other way to play local files from the mobile, apart from Upnp AV protocol?

Goal here is, 
1. Play music from phone/sdcard and
2. Play music from online service.
3. Have a common playlist. Shareable, open.
4. Multiroom.

From what I understand, snapcast offers 2, 3 and 4 in combination with Mopidy.
What about 1? How flexible is it? What are my options? _That is plural!_

**Comment by ThYpHo0n** [comment]
For 1 I use AirPlay, I‘m totally in the Appleverse, if you’re on Android I dunno if there is a good Airplay player which can stream local music via Airplay? On the other side maybe there is something similar for Googlecast which can be piped to Snapcast.

**Comment by herrwusel** [comment]
> Goal here is,
>    Play music from phone/sdcard and

Bubbleupnp might be the right app for you. It can stream to upnp devices from your phone's sd card and also supports cloud services. If your phone is rooted you can even use their xposed plugin which is quite nice.

**Comment by totti2** [comment]
I am piping Bluetooth into Snapcast.
I found [this](https://github.com/BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install) which I installed first thing after flashing my SDCard. Then I installed Snapcast.

I added a sink to the respective line in my /etc/default/snapserver
`-s pipe:///tmp/snap_blue?name=Bluetooth&mode=read`

I added a PulseAudio pipe-sink (adapted from Snapcast-docs)
`load-module module-pipe-sink file=/tmp/snap_blue sink_name=bluetooth`

Find sinks and sink-inputs and combine them
`sudo pactl list sinks
sudo pactl list sink-inputs
sudo pactl move-sink-input #N SINK|SOURCE`

**Comment by BaReinhard** [comment]
hey @badaix I really am enjoying your repo/project. It simplifies multiroom audio to a great extent without having to fork over $$$ to companies like sonos or google (although I do have a repo for multiroom with chromecasts). I was originally turned on to yours as a request on an issue for my Audio Receiver repo, one thing led to another and here we are.

I have recently added some snapcast support to my existing repo [here](https://github.com/bareinhard/super-simple-raspberry-pi-audio-receiver-install). It is still in BETA as of right now because I'm still trying to get the hang of all its functionality, but I believe that both of these repos could work well in unison, I currently have airplay and bluetooth (auto pairing and connection) on raspbian Jessie Lite.

With some configuration I believe that my repo could help solve this current issues problem possibly some others? To me it seems that there may be a large demand for easy connection via bluetooth or airplay to a server, which can output to multirooms. I am currently in the works of making a script to solely install automated bluetooth connection for existing Raspbian Images so that users don't need to be married to my idea of a receiver installation and can cherry pick what they would like.
