### ISSUE TITLE
Can I use RTP protocol to replace the TCP one?

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#305]
I want to achieve a multi-room function in our existing system. however, we used the RTP protocol for connection since we had some other functions. So, I want to know whether we can use the RTP rather than TCP, in snapcast.
Looking forward to your reply. Thanks!

**Comment by philippk80** [comment]
Snapcast uses TCP to communicate with each other and I think it has its own "protocol".
RTP uses UDP for data transmission and needs another protocol to do the control. 
For example RTCP can be used. This protocol is doing the controlling over TCP.

For sure it could be forked or implemented here but I don't think the creator of snapcast has any profit doing this. He is the one doing the most like the statistics on Github show.

**Comment by badaix** [comment]
Hi, I've choosen a proprietary protocol over TCP to achieve synchronous playback on the clients at high audio quality. 
In RTP it's possible to loose packets, as it is running on top of UDP. Also it doesn't have absolute timestamps, but only a timestamp based on a frame counter to interleave audio and video on one client.
Disadvantage of TCP of course is that it is connection oriented and thus not multicast capable (in multicast a client could not get resent a dropped packet, which would lead to drop-outs in the audio stream).
Also it seems that WiFi routers do unicast instead of real multicasting, as pointed out [here](https://github.com/badaix/snapcast/issues/90#issuecomment-233122877). As the purpose of Snapcast is the synchronous playback within a house or apartment with not too many clients attached (let's say up to 10), it will for most users run over a WiFi connection.
The ideal protocol would be something like RTP (multicast capable) with absolute timestamps and some control protocol that could request single packets if they are missing.

**Comment by philippk80** [comment]
Is this the common approach from protocols like dante?

**Comment by mightyCelu** [comment]
I think RTP might still be a viable alternative. Using UDP also reduces channel load in WiFi settings as no acknoledgements need to be sent. Since high channel load is one of the major reasons for packet loss in wireless networks, this would could improve service quality.

By complementing it with RTCP, one could overcome the issues with using only RTP:
- RTCP can report absolute timestamps for synchronizing streams, this way absolute timestamps can be computed from RTP's relative ones.
- RTCP specifies receiver reports (RR) which communicate packet loss statistics. Additionally, RFC3611 defines an extension which can be used to communicate loss of individual packets. Of course, since RTCP also uses UDP, these reports, too, might be lost but I reckon this double-loss-event is very unlickely.

The problem with multicast on WiFi is, that it falls back to very conservative codings to ensure delivery, thus using large amounts of airtime. However it'd be great if one could support multicast for e.g. wired deployments or future improvements of wireless technology/standards in this area.
Also, using standardized protocols would improve interoperability and create less effort in some ports e.g. documentation of the protocol would be much simpler.

**Comment by christf** [comment]
Having spent quite some time with building a community wifi network (see Freifunk.net) with many nodes, I feel that unicast really is the way to go. multicast is limited to 11Mbps, often defaulting to 1Mbps.
That being said, on top of that a protocol needs to be implemented that compensates for lost/dropped packets. 

in clientConnection.cpp the communication socket is opened in tcp-mode, seemingly since april 2016 using the default send and receive timeouts.
before that 5seconds seems to have been used as timeout value.

I feel this is not ideal yet. These timeouts and retransmit options should scale with the size of the buffer. For example - I know I am using a horribly unstable wifi, so I use a large buffer of 20 seconds. Unfortunately I still get audio dropouts and it seems like tcp does not cope well enough with the bad network situation to avoid these. I do not care much about real-time audio - My use case is to listen to some music that should play continously without dropouts. If it helped I would set a minute buffer :-D. 
Using larger buffers with the current socket configuration will not help my dropout situation at the moment.

I wonder whether there is a possibility to obtain more control on the tcp retransmit options or whether a switch to UDP and manually taking care of re-transmits is the way to go here.

**Comment by christf** [comment]
I am just re-visiting this issue because I am working on stabilizing audio output for my setting.

TCP has the advantage that we do not have to engineer much of a protocol on top of it. If we do anything on UDP at least in the easiest implementation we would not gain on TCP due to missing ACKS because there the packets would have to be requested. Client to server: "please send me the packet for time slot X".

This scheme would require a server and a client buffer of equal size. Also this would allow us to start playing before the buffer is completely filled. This could be helpful on XRUN-type situations.
It would require a rework of the streaming and buffering code and be quite a bit of work.

Seeing how dropouts due onResync are currently the root cause of the most audio dropouts I am seeing here, it might be enough to address just that.

**Comment by christf** [comment]
Having spent some more time with snapcast I think that with TCP there is not enough control over the packet stream when using WIFI.  Implementing RTP would be an approach or building a custom protocol that is based on UDP. Servertimestamp, sequence number and data should be sufficient for regular data packets when there is a hello/control that is used to transport the format of the stream.

There is jrtplib http://research.edm.uhasselt.be/jori/page/CS/Jrtplib.html which allows usage of RTP in c++.

**Comment by badaix** [comment]
As pointed out, RTP is not an option, but a hand crafted UDP protocol is on the roadmap (TODO.md), because TCP has the problem with head of line blocking. It will retry sending chunks that should have been played seconds ago, and, if eventually transmitted, will be dropped on the client.
