### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by j0s** [badaix/snapcast#32]
I see that there's been a lot of interesting developments in the `develop` branch since 0.4.0. Is it getting ready for a release anytime soon? Thanks for developing this awesome piece of software!

**Comment by badaix** [comment]
Hi @j0s,
I've just released a preview of the v0.5: https://github.com/badaix/snapcast/releases/tag/v0.5.0-beta-1
Key features:
* Support for multiple streams
* Remote controller API (JSON syntax)
* Android port of the Snapclient
* Combined Android remote controller and player app

**Comment by pille** [comment]
just a quick comment of my experience with this release:
* compiled and worked on Linux Mint (32bit) with Gentoo (64bit) after one gets used to the submodules...
* i have the feeling my music is pitched up a little bit. perhaps due to dropping frames for syncing.
* installing the android-apk results in "There was a problem parsing the package" on Android-4.1.2

**Comment by badaix** [comment]
Hi @pille,

thanks for the feedback.

* Concerning submodules, I've updated the [Readme.md]   (https://github.com/badaix/snapcast/blob/develop/README.md):

> After cloning the Snapcast repository, you have to update the external submodules:
> 
>     $ cd <MY_SNAPCAST_ROOT>/externals
>     $ git submodule update --init --recursive
>     
> Build Snapcast by cd'ing into the Snapcast src-root directory:
> 
>     $ cd <MY_SNAPCAST_ROOT>
>     $ make
> 

* The pitch is because the default sample rate is changed from 44.1kHz zo 48kHz.
The [release notes](https://github.com/badaix/snapcast/releases/tag/v0.5.0-beta-1) are updated:

> ## General
> * Changed default sample rate to 48kHz. The sample rate can be configured per stream `-s "pipe:///tmp/snapfifo?name=default&sampleformat=44100:16:2`. The default can be changed with `--sampleformat 44100:16:2`
> 

* About Android: The NsdManager - doing the zeroconf discovery - requires at least API level 16 (Android 4.1) and figuring out the native sample rate (`AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE`) needs API level 17 (Android 4.2).  
This is actually not really a necessary feature. It's only there to issue a warning, if the stream's sample rate doesn't match your device's native sample rate. In this case the device will not play in sync. It gets even worse when the display is turned off.   
Seems that the OpenSL implementation performs bad in resampling.  
I lowered the requirement to API level 16 and show a warning that the sample rate of the stream should match the native sample rate of the device. The [APK](https://github.com/badaix/snapcast/releases/download/v0.5.0-beta-1/Snapcast-0.5.0-beta-1.apk) is now updated. Please try again.

**Comment by pille** [comment]
thanks for your swift reply and clarification, @badaix.
* indeed forcing the samplerate back to 44.1KHz restored my familiar music experience ;-)
* the new APK could be installed, but lacks any use. after some time it found a server, but it's showing an IPv6 address, which got truncated due to its length. however it's not the address of the server. probably it's the link-local address of the android device, but it won't show that info easy.

**Comment by pille** [comment]
neither have-you-tried-switching-it-off-and-on-again, nor re-scanning did anything.
i'll try on an android-5 within the next days...

**Comment by happyleavesaoc** [comment]
A note for those using Mopidy - you can conform to the 48k rate like this:
```audioconvert ! audioresample ! audio/x-raw, rate=48000 ! filesink location=/tmp/snapfifo```

**Comment by pille** [comment]
works on android-5.1. just tested server discovery, connect and volume change.

**Comment by pfink** [comment]
So I think this can be closed?

**Comment by badaix** [comment]
@pfink I like this issue #32 as kind of a discussion thread for new releases :wink:

**Comment by pfink** [comment]
Well, fair enough :smiley:
