### ISSUE TITLE
only 1 client showing in snapcast 

### ISSUE THREAD

**Issue by palitu** [badaix/snapcast#337]
I have a weird issue where i am trying to configure numerous snapclients, but only one will dispaly in the snapcast app.  If i configure an instance number, i see unique clients in the app, which are appended with the instance.

I am running snapclient 0.12.0_armhf.deb on dietpi for OrangePi Zero.

Is there any logs files that will help? 

thanks.

**Comment by maweki** [comment]
Probably duplicate of https://github.com/badaix/snapcast/issues/299

Use `--hostID` to overwrite the id. Otherwise https://github.com/badaix/snapcast/commit/3e351062e16878944166165190d9391b989e5acd will fix the issue in the next release if (and I've seen this with cheap devices from china) the MAC addresses are indeed unique, as they should be.
