### ISSUE TITLE
Client switching groups

### ISSUE THREAD

**Issue by frequency17** [badaix/snapcast#352]
I have two groups set up, one of which is set to stream a file. When using JSON-RPC to change the assigned group for a client, the client continues to play the stream assigned to its former group. The group status call shows that the client is assigned to the new group. Restarting the client causes it to play the stream of the new group.

**Comment by danpowpow** [comment]
@frequency17 can you explain how you have set groups up? I am struggling with this - editing the server.json file with group info doesn't work for me - it only gets re-written on reboot.
I have two clients per floor, that i would like to 'group' off so that each floor can recieve its own stream/pipe
