### ISSUE TITLE
Make a single client "master"

### ISSUE THREAD

**Issue by vdbee** [badaix/snapcast#43]
Would it be possible to make the clients configurable to operate in master-slave operation. This would enable definition of a single master that does not drop frames or adapts speed while other possibly mutliple clients adapt their timing to this "holy" master?

**Comment by s1lvester** [comment]
So you want to reroute another time-signal through your already overloaded network that produces skips?

**Comment by pfink** [comment]
Another solution would be to extend the server functionality. Then the server could act as this master client as well, so that no additional traffic is produced.

**Comment by sp4ceman** [comment]
@s1lvester i don't know if it would add a time-signal if a main client is just sort of "playing the song" locally while the rest of the clients use the sync mechanism.

**Comment by vdbee** [comment]
I indeed had in mind to extend the server's functionality. I made this request because I suffered quite some stuttering during playback, also on the server side. However, I reconfigured my asound.conf to achieve achieve playback at server side without having snapclient there. Although it did not solve the stuttering (I will try a faster SD-card), this asound.conf enables running snapcast in combination with Spotify-connect-web and Mopidy on OSMC all sharing the same USB-DAC

# DEFAULTS
pcm.!default {
        type plug
        slave.pcm "fifo"
        hint.description "Dmix to both FIFO and USB DAC"
}
ctl.!default {
       type hw
       card 0
}

# SOFTWARE MIXING
pcm.dmix_usb {
    type dmix
    ipc_key 1024
    ipc_perm 0666 # allow other users
    slave.pcm "usbdac"
    slave {
        period_time 0
        period_size 1024
        buffer_size 4096
        channels 2 # must match bindings
	rate 44100
    }
    bindings {
        0 0
        1 1
    }
}

# OUTPUT USB-DAC
pcm.usbdac {
        type hw
        card 1
        hint.description "USB DAC"
}

# OUTPUT FIFO buffer
pcm.fifo {
    type rate
    slave {
        pcm writeFile # Direct to the plugin which will write to a file
        format S16_LE
        rate 44100
    }
}
pcm.writeFile {
    type file
    slave.pcm "dmix_usb"
    file "/tmp/snapfifo"
    format "raw"
}

**Comment by pfink** [comment]
@vdbee: But this doesn't make so much sense because you'll loose synchronicity. If you don't have the requirement to play audio **synchronous **, you should not use snapcast. In this case, you can use any software that supports audio streaming (e.g. pulseaudio) and it'll work much better than snapcast.

**Comment by vdbee** [comment]
@pfink: Yes, you're completely right. I renounced synchronous playback in an attempt to get rid of my stuttering issue. However, I should have made that explicit in my comment. I'll update it right away.

**Comment by badaix** [comment]
If you "hear" the stuttering even locally then something else is going wrong. I only experience audible drops when I have problems with my WiFi connection.
At some point you always have to resync somehow. There is always some small buffer involved and soundcards that play at 48003 Hz instead of 48000 Hz, which is slowly eating up you buffer. 
I could imagine to be more tolerant when to resync: when you start the snapclient manually in a shell, you will see three audio buffers and their mean deviation from the perfect sync. If they exceed certain thresholds, a resync will happen (drop packets, play faster, ...).
Maybe you can try this and if it looks "wild" instead of "smooth" you can copy paste some of the log messages here.
