### ISSUE TITLE
Pipe from librespot plays too fast

### ISSUE THREAD

**Issue by dflvunoooooo** [badaix/snapcast#464]
If I redirect the librespot output via pipe to a snapcast fifo file the music is a little bit to fast, just enough to be noticed and to nag. This happens as well with the `… --backend pipe >` or with `--backend pipe --device /tmp/snapfifo-Spotify` of librespot.

If I start librespot without the pipe option and redirect it via pulseaudio to snapcast it plays in normal speed.

There is no error message nor anything wich would show a problem. I use librespot 12.1.51-7 on a Arch Linux desktop. And the guys from librespot told me, it is a snapcast problem, because librespot writes as fast as possible to the fifo file and snapcast has to handle the playback [https://github.com/librespot-org/librespot/issues/340#issuecomment-504499635](url).

Has anyone an idea how to solve this issue? I would like to run librespot with snapcast on a headless server, wich will not have pulseaudio.

**Comment by petershaw23** [comment]
setting your sample rate to 44khz should fix this

**Comment by dflvunoooooo** [comment]
Thank you very much, that fixed it! Should have thought of it myself.

**Comment by kingosticks** [comment]
@petershaw23 Out of interest do you know why this is necessary?

**Comment by petershaw23** [comment]
not really, my guess is that spotify stores all their music as 44khz and
resampling doesn't work?

Am Di., 2. Juli 2019 um 12:27 Uhr schrieb Nick Steel <
notifications@github.com>:

**Comment by kingosticks** [comment]
That's the weird thing, Spotify audio data is definitely 44.1kHz.

**Comment by petershaw23** [comment]
yes, we were talking about 44**,1** all along. just to lazy to type it out :)

**Comment by kingosticks** [comment]
Ahh OK thanks for clarifying that.

**Comment by itskevinb** [comment]
Hitting this in 2026-05 with a snapcast multi-room setup, writing up the fix in case it helps someone else.

**Symptom:** With `librespot --backend pipe` writing to `/run/snapfifo` consumed by snapserver, tracks would *load* in rapid bursts (multiple per second in librespot logs) but no audio ever flowed — snapserver `stream` status stayed `idle`. Spotify mobile/web/desktop would auto-skip through the entire queue within seconds, then mark the device inactive. `WARN librespot_connect::state::context] couldn't load context info because: context is not available. type: Default` was consistently present.

Same librespot binary, same Spotify account: `--backend alsa` endpoints (Music Room with a real ALSA device) worked perfectly. Only the pipe-backend endpoint failed.

**Things that did NOT help in our case** (worth listing so others can skip them):
- librespot dev branch HEAD vs 0.8.0 release
- `--autoplay off`, `--disable-gapless`
- Renaming the device, clearing cached credentials, Spotify "Sign Out Everywhere"
- Direct `librespot ... > /run/snapfifo` (no ffmpeg)
- Adding `ffmpeg -re` as a real-time pacer (this is sometimes recommended, but in our case librespot was idle in `do_epoll_wait` and ffmpeg had `wchar=0` — pacing isn't the issue when librespot isn't writing in the first place)
- Switching the host from an unprivileged LXC to a full VM (ruled out container kernel quirks)
- 44.1k end-to-end (no resample), snapclients resampling locally

**What fixed it:** switching from `--backend pipe` to `--backend alsa` via `snd-aloop`, mirroring our working ALSA endpoints.

`/etc/modules-load.d/snd-aloop.conf`:
```
snd-aloop
```
`/etc/modprobe.d/snd-aloop.conf`:
```
options snd-aloop pcm_substreams=1
```

Rebuild librespot with the alsa feature (cargo's default install lacks it):
```
cargo install librespot --version 0.8.0 --force --locked --features alsa-backend
```

librespot launcher (`librespot-innout.service`):
```bash
exec librespot --name "MyEndpoint" --backend alsa --device hw:Loopback,0,0 \
  --format S32 --bitrate 320 --device-type speaker \
  --cache /var/cache/librespot --zeroconf-port 5051
```

Separate bridge service that reads the loopback capture side and writes PCM to snapfifo (`snapfifo-bridge.service`):
```bash
exec ffmpeg -nostdin -loglevel error \
  -f alsa -acodec pcm_s32le -ar 44100 -ac 2 -i hw:Loopback,1,0 \
  -af aresample=resampler=soxr:precision=28:dither_method=none \
  -ar 96000 -ac 2 -c:a pcm_s32le -f s32le pipe:1 \
  > /run/snapfifo
```

snapserver source: `pipe:///run/snapfifo?name=MyEndpoint&sampleformat=96000:32:2&codec=pcm`.

The snd-aloop kernel module gives librespot a real-time-clocked audio sink (which the pipe backend doesn't), and Spotify's Connect controller then treats the device normally. Snapserver stream goes to `playing` within a second of pressing play and stays there.
