### ISSUE TITLE
bluetooth speaker lag?

### ISSUE THREAD

**Issue by sp4ceman** [badaix/snapcast#50]
i have a raspberry pi running snapserver and mopidy and then i have installed your android apk onto my phone. when running the client over my phone speaker or a cable connected to my phone its amazing but when i hook my phone up to a bluetooth speaker it gets out of sync quickly and just lags.

is this a known issue? it makes sense theres an extra delay via bluetooth but didn't see anything mentioned so i thought i would ask.

ps thank you for an amazing project!

**Comment by badaix** [comment]
The Snapclient for Android is a native binary, cross compiled for Android. This is important (besides it is less effort) because it can use OpenSL as low level, low latency audio player. It has a defined buffer size and it's quite good predictable when an audio sample is played out.
I don't know how BT is routed, but I guess it sits somewhere behind OpenSL, that is playing to `SL_ANDROID_STREAM_MEDIA`. I think it might be OEM dependent.
At least one additional recoding (SBC, MP3, AAC, ATRAC) is required for Bluetooth audio. So you will have some additional processing, buffer and latency - also in your speaker/renderer. 
When you're lucky, the latency is constant (I doubt, but who knows). This constant latency can by configured in [ms] with the Android App.

**Comment by sp4ceman** [comment]
thanks, i figured it would be something like that.
i'm not really all that familiar with "lower level" code like this (i live in .net land) and so its interesting for me just to know how and try see what how "pipeline" for the different audio works. 

thanks for you input.

**Comment by ThYpHo0n** [comment]
@sp4ceman The main problem in your scenario is the A2DP connection between your phone and the bt speaker this adds latency into your audio pipeline which results in an asynchronous playback. There is no (easy, if at all) way to fix this latency. You can increase the buffersize but this doesn't ensure it keeps synchronous and A2DP doesn't support times like RTSP. You need this timing info in your protocol because the Bluetooth connection works kinda networkish and gets occasionally higher response times which you have to countermeasure in some way.

**Comment by sp4ceman** [comment]
once again thanks for the info. :)
