### ISSUE TITLE
Error making macos client (missing submodules)

### ISSUE THREAD

**Issue by ClemGogby** [badaix/snapcast#510]
Hello! I'm trying to update my snapcast client to the latest release but it looks like some of the needed external submodules are missing. I compared the externals between 0.17.1 and 0.16.0 and noticed that the submodules are indeed different. Here's the error I get when I try to make the client:
`$ make TARGET=MACOS
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DVERSION=\"0.17.1\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c snapclient.cpp -o snapclient.o
In file included from snapclient.cpp:25:
In file included from ./controller.hpp:36:
./client_connection.hpp:25:10: fatal error: 'boost/asio.hpp' file not found
#include <boost/asio.hpp>`

**Comment by badaix** [comment]
Looks like you don't have boost installed

**Comment by ClemGogby** [comment]
Ah. I should have done a quick google about that and notice that boost is something I can install with homebrew. Sorry about that.

So, I installed boost through homebrew, and then I got an error about opus. So I installed that through homebrew as well.

So I was able to build snapclient, but when I try to install it, I get a new error:
```
$ sudo make install TARGET=MACOS
echo macOS
macOS
install --strip -g wheel -o root snapclient /usr/local/bin/snapclient
install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

**Comment by jasondavis87** [comment]
I'm also getting this error ... exactly the same message ... bump :)

**Comment by badaix** [comment]
Can anyone owning a Mac try to fix the problem? Looks like the `install` command doesn't like the `--strip` option. Following the BSD man page, `install -s -g wheel -o root snapclient /usr/local/bin/snapclient` should work.
Can you replace the line `install --strip -g wheel -o root $(BIN) $(TARGET_DIR)/local/bin/$(BIN)` in `client/Makefile` with `install -s -g wheel -o root $(BIN) $(TARGET_DIR)/local/bin/$(BIN)` and try again?

**Comment by serussell** [comment]
@badaix, I successfully built the project on my wife's Macbook.  I did not find the OSX branch until well into the process; that branch may build fine by itself.  Main changes that were needed on Master were:

1. Additional dependencies: opus & boost (`brew install opus boost`)
2. Wiki instructions need updating: `sudo make install ...` needs to be `sudo make installclient ...`
3. Remove `--strip` from the `make install ...` command in `client/Makefile`
4. Copy `client/etc/snapclient.plist` over from the OSX build branch and change the location in `client/Makefile`

I'd done the first three by the time make errors let me to try to find the plist file, which led me to discover the other branch.  What I ended up doing -- since the build was successful and I was on the install step -- was copying `client/Makefile` and `client/etc/snapclient.plist` into Master and continuing the install; that was all that was necessary for the final installation.  With those changes it is running fine on her laptop, and has been tested with a Linux laptop and her Laptop playing holiday music, which has thrilled my wife.  So, thanks from her, as well as myself.

**Comment by badaix** [comment]
Thanks @serussell for figuring this out. 
As discussed in #514, the develop branch might work out of the box. `plist` is reintroduced there and also the readme is updated to mention `opus` and `boost`. In the makefile `--strip' is replaced by `-s` which should do the stripping of the binary.

**Comment by artmg** [comment]
Hi, I tested the develop branch as of today (see checksum in branch below)

```
# 0. get a local copy of the repo
$ git clone https://github.com/badaix/snapcast/
$ cd snapcast/
$ git checkout develop

# 0.5 check the commits
$ git branch -v
# * develop 8613e1f Add Android arm64 support
#   master  ec2e7b2 Update instructions to include opus dependencies

# 1. command line to for xcode tools
$ xcode-select --install
# accepted prompt to Install around 130 MB of command line dev tools

# check versions
$ sw_vers -productVersion
# 10.14.6
$ xcode-select --version
# xcode-select version 2354.

# 2. installed homebrew from http://brew.sh/

# 3. deps
$ brew install flac libvorbis boost opus

# 4. build snapclient

$ cd client
$ make TARGET=MACOS

# this gave only one warning (macos support is experimental) and created: 
# snapclient  browseZeroConf  player  decoder
# and  controller.o  time_provider.o  client_connection.o  stream.o  snapclient.o

# 5. install snapclient
$ sudo make install TARGET=MACOS

# echo macOS
# macOS
# install -s -g wheel -o root snapclient /usr/local/bin/snapclient
# install -g wheel -o root snapclient.1 /usr/local/share/man/man1/snapclient.1
# install -g wheel -o root etc/snapclient.plist /Library/LaunchAgents/de.badaix.snapcast.snapclient.plist
# launchctl load /Library/LaunchAgents/de.badaix.snapcast.snapclient.plist

```

I did not validate all the changes @badaix mentioned above, I just plugged in the instructions from the readme in that branch/commit and the right result popped out. As far as I can tell, as long as you **`git checkout develop`** then the build process is currently working. :)
