### ISSUE TITLE
Build Docker image

### ISSUE THREAD

**Issue by KamilLenica** [badaix/snapcast#513]
Please provide Docker image, preferably for armhf arch based on alpine Linux

**Comment by badaix** [comment]
I'm not planning to provide docker images, I'm having enough trouble providing the debian packages.
Packaging should be done outside of this project. There are some docker containers around, e.g. [docker-snapcast](https://github.com/nolte/docker-snapcast)

**Comment by KamilLenica** [comment]
I was not aware of that, thank You

**Comment by Saiyato** [comment]
Hi @badaix ,

I'm willing to pick this one up, I've managed to get it up-and-running on raspbian container images. However, I'd like to minimize the footprint, so my preference is (just like @KamilLenica) being able to build on Alpine images. I'm almost there I think, at least for the snapclient part, I still have to investigate dependencies for the server.

As for the build street now, the resin/raspbian:jessie|buster image is working as intended. I see nolte used ubuntu instead, not sure if that makes a lot of difference, but his images are are very old. He did provide for the Dockerfiles though ;)

Still working on the details, and if it's all the same, the Alpine images can be as small as <20 megs, so that's obviously preferable to 80 megs. You can follow the progress on [Docker Hub](https://hub.docker.com/repository/docker/saiyato/snapclient/builds)

**Comment by l3d00m** [comment]
Thank you @Saiyato, this is great and looks much better than all other snapcast docker projects (since it's not just using the deb)

**Comment by Saiyato** [comment]
Just updated the scripts for the containers, the following architectures are supported by pulling :latest

- arm32v6
- arm32v7
- arm64v8
- amd64

The GitHub and DockerHub readme pages provide information on usage.

There is still an i386 container, but Docker requires a 64bit OS on x86_64 so it doesn't add much. 

Both the server (with snapweb) and client containers are provided on Alpine base images. Tested with Snyk on vulns (0 at the time of writing). Daily scans have been scheduled for remediation.

Have fun!
