### ISSUE TITLE
Change / disable stream watchdog timeout

### ISSUE THREAD

**Issue by uSpike** [badaix/snapcast#517]
I have a few different librespot streams:
```
stream = spotify:///librespot?name=Spotify_Me&bitrate=320&volume=100&username=a&password=b
stream = spotify:///librespot?name=Spotify_Wife&bitrate=320&volume=100&username=x&password=y
```
I find that when off, the stream watchdog kills/restarts librespot every 7800 seconds.  
```
Dec 21 14:28:00 music snapserver[15394]: 2019-12-21 14-28-00 [Err] Spotify timeout: 7800
Dec 21 14:28:00 music snapserver[15394]: 2019-12-21 14-28-00 [Err] (PipeStream) Exception: end of file
```
Because of this, sometimes players will not see the librespot device in the connect device list.

Is it currently possible, or could a feature be added, to change the timeout period or disable it entirely?

In the meantime, I may move to managing librespot with a separate process manager.

**Comment by uSpike** [comment]
It appears this was implemented in 6d7e25e9af8720743d4b197e41d271b169be3e29

**Comment by badaix** [comment]
exactly, you can configure the timeout now. When you set it to 0, it's deactivated. Although, it shouldn't be neccessary to disable the wd. After some years I've reactivated my Spotify account and I'm using it for a couple of weeks now without any issues, the WD is running, but doesn't kill the process.
Don't know if the wd is still needed, but ~3 years ago Librespot stopped working from time to time (maybe it was simply because of my nightly DSL disconnect, I don't know).
Please try out the new version, I will build some APKs soon.

**Comment by badaix** [comment]
f
