### ISSUE TITLE
Documentation lists the wrong file for configuration files

### ISSUE THREAD

**Issue by KraigoMpls** [badaix/snapcast#535]
The documentation on the main SnapCast github page (https://github.com/badaix/snapcast) lists "/etc/default/snapserver and /etc/default/snapclient" as the configuration files for SnapCast.  A look through the source did not immediately reveal where the default configuration file should be for SnapClient, but the SnapServer code and a test confirmed that the current location for the its configuration file is /etc/snapserver.conf.

Is there still a working equivalent for SnapClient?

Thanks in advance.

KO

**Comment by badaix** [comment]
The documentation states that:

> After installation, Snapserver and Snapclient are started with the command line arguments that are configured in /etc/default/snapserver and /etc/default/snapclient. Allowed options are listed in the man pages (man snapserver, man snapclient) or by invoking the snapserver or snapclient with the -h option.

which is true:
```bash
pi@raspberrypi:~ $ cat /etc/default/snapserver 
START_SNAPSERVER=true
SNAPSERVER_OPTS=""
```
So Snapserver is started without any special options. In the next paragraph it clearly states that the server configuration is done in `/etc/snapserver.conf`:

> The server configuration is done in /etc/snapserver.conf. Different streams can by configured in the [stream] section with a list of stream options, e.g.:

Let's check the allowed command line options mentioned in the previous paragraph `snapserver -h`:
```
pi@raspberrypi:~ $ snapserver -h
Allowed options:
  -h, --help                          Produce help message
  -v, --version                       Show version number
  -d, --daemon [=arg(=0)]             Daemonize
                                      optional process priority [-20..19]
  --user arg                          the user[:group] to run snapserver as when daemonized
  -c, --config arg (=/etc/snapserver.conf)
                                      path to the configuration file
```

`-c, --config arg (=/etc/snapserver.conf)  path to the configuration file`

The empty `SNAPSERVER_OPTS=""` in `/etc/default/snapserver` means that the default `/etc/snapserver.conf` is used for `--config`, because it's not specified else wise.

For me the documentation is clear and correct. Any suggestions to make it even more clear are welcome.

**Comment by KraigoMpls** [comment]
Thank you for the very thorough and patient explanation.  It's a pity that it will get lost here.  Could you paste that someplace where users will find it?  It's wonderful!

**Comment by badaix** [comment]
Sorry, I had a short night.
