### ISSUE TITLE
No OpenWrt builds since 0.12.0

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapcast#551]
Looking at the [release page](https://github.com/badaix/snapcast/releases/), it appears there have been no OpenWrt builds (.ipk packages) since 0.12.0.

These should either be restated or OpenWrt should be removed from the list of available flavours for Snapcast.

**Comment by xabolcs** [comment]
See SnapOS, which have OpenWrt flavour, and also a little bit newer release: 0.15

OpenWrt related document leftovers should cleaned up from here and advertise the SnapOS repository.

Sure, a new OpenWrt release would be nice.

**Comment by badaix** [comment]
Agree, there should be just a link to SnapOS at least for an how-to-build.
I haven't used my router as playback device for a while (must be since 0.15), so there are no ipk's.
Also the packages were just built for my specific MIPS CPU. The only meaningful approach would be to find out how to become an officially supported OpenWRT package and make it into this list: https://openwrt.org/packages/index/sound
I hope that the OpenWRT toolchain supports C++14, which Snapcast is using since 0.16 (Android and - I think - OpenWRT were supporting just a subset of C++11 back then, for Android the situation changed, don't know about OpenWRT).

**Comment by xabolcs** [comment]
> I hope that the OpenWRT toolchain supports ...

With a few changes I was able to compile Snapcast to MIPS, MIPSEL and ipq40xx when I was working on #490.
OpenWrt supports Boost 1.71 too! :+1:

**Comment by xabolcs** [comment]
> The only meaningful approach would be to find out how to become an officially supported OpenWRT package and make it into this list:

The official workflow is here, in GitHub: https://github.com/openwrt/packages/tree/master/sound

Just open a PR and it's done!

**Comment by badaix** [comment]
The [openWRT makefile](https://github.com/badaix/snapos/blob/master/openwrt/snapcast/Makefile) is now updated to Snapcast v0.18.1, version 0.19 will additionally depend on libsoxr (which is available in openWRT). Once v0.19 is released, I will polish the and update the openWRT Makefile and make a PR for an openWRT package

**Comment by axelsimon** [comment]
Great stuff. Thanks @badaix.
I think this issue has served its purpose, i'll go ahead and close it now.
