### ISSUE TITLE
icecast support

### ISSUE THREAD

**Issue by prietus** [badaix/snapcast#585]
does snapcast support piping to icecast?

**Comment by xabolcs** [comment]
What usecase do you have, that you need support Snapcast piping to Icecast(2?)?

**Comment by badaix** [comment]
no, and I also cannot imagine a usecase for that.
Purpose of Snapcast is to play synchronously on several clients, using low level audio APIs and not to forward the audio stream to icecast.

**Comment by Gwynei** [comment]
I'm trying to figure out a way to let legacy devices be a part of a snapcast setup - if snapserver would support outputting a shoutcast/icecast compatible stream that would definitely solve my issue.

@badaix any plans for that?

**Comment by xabolcs** [comment]
I added HooToo HT-TM02 (Ralink RT5350, MIPS24KEc 360 MHz, 32 MB RAM, 8 MB ROM) + UCA-202 + OpenWrt as a Snapclient to my Snapcast setup.

How does this compare to your legacy devices? @Gwynei

**Comment by badaix** [comment]
@Gwynei Snapserver will never support any other client than the Snapclient. If ever there is icecast support, then only via an icecast audio backend in the Snapclient. This should be possible already through redirection of the alsa or pulse or file backend.

**Comment by Gwynei** [comment]
> How does this compare to your legacy devices? @Gwynei

@xabolcs Background story is that it's about a software client with shoutcast/icecast support only. I thought of using mopidy/snapserver/snapclient as a replacement of [butt](https://danielnoethen.de/butt/)/icecast. I'm starting to realize those tools are not comparable on all levels. Just the [mopidy documentation](https://docs.mopidy.com/en/latest/icecast) pushed me towards the snapcast direction:

_"You cannot stream from Mopidy via Icecast with the below method when using Ubuntu 20.04 or Debian Bullseye. **Consider Snapcast as an alternative solution**."_


> @Gwynei Snapserver will never support any other client than the Snapclient. If ever there is icecast support, then only via an icecast audio backend in the Snapclient. This should be possible already through redirection of the alsa or pulse or file backend.

@badaix Fair enough. I guess I could make things work using mopidy and snapcast, outputting to icecast, but I just need to figure out how I can make that work, preferably without using [butt](https://danielnoethen.de/butt/). I will not ask you for a step by step tutorial, but could you point me into the right direction?

**Comment by kingosticks** [comment]
> "You cannot stream from Mopidy via Icecast with the below method when using Ubuntu 20.04 or Debian Bullseye. Consider Snapcast as an alternative solution."

I would assume they've since fixed libshout but I've no interest in checking the state of it in the latest Ubuntu/Debian releases. If someone is interested it'd be great to update that notice and remove the warning.

**Comment by ckcr4lyf** [comment]
FWIW: I wanted this exact usecase, since I am trying to use a microcontroller as a client, which has easy support for playing an "ICY MP3" stream over HTTP (for instance [ESP8266 audio example](https://github.com/earlephilhower/ESP8266Audio/blob/12131e9826283ec19cc728476c1dc1479bb7c09d/examples/StreamMP3FromHTTP/StreamMP3FromHTTP.ino))

To do this, I did a rather roundabout way of:

```
Librespot (Spotify) -> Snapserver -> Snapclient -> Ffmpeg -> Icecast -> Microcontroller (via HTTP MP3 stream)
```

The reason for not piping librespot directly to ffmpeg/icecast , is I can still have some snapcast clients as well, with Snapserver in the middle.

The exact command I used to pipe the snapclient via ffmpeg to icecast is:

```
snapclient -h 127.0.0.1 --logsink stderr --player file | ffmpeg -f s16le -ac 2 -ar 44100 -re -i pipe:0 -map 0:a:0 -c:a:0 mp3 -b:a:0 320k -content_type audio/mpeg -f mp3 icecast://source:password@127.0.0.1:8000/bruvva.mp3
```

Between clients the delay can sometimes be as much as 2-3 seconds , but for my usecase I am ok with this. There are some microcontroller snapcast projects as well, which seem interesting, e.g. https://github.com/jorgenkraghjakobsen/snapclient
