### ISSUE TITLE
Switch to cross-platform binary protocol

### ISSUE THREAD

**Issue by bjab** [badaix/snapcast#590]
Hi

Did you consider switching from custom made protocol to something that can be easily adapted in multiple languages?
Something like [flatbuffers](https://google.github.io/flatbuffers/) or [Cap'n'Proto](https://capnproto.org/) (flatbuffers is better for snapcast in my opinion :))

It would allow to easily implement additional clients.

**Comment by badaix** [comment]
Not at the moment, I've actually switched from Protobuf to a hand craftet protocol years ago, having the advantage that no code has to be generated at any platform (otherwise you need a code generator for Windows, Android, Linux, Mac, ...), although defining the protocol in an IDL is more elegant and endianness independent.
But currently there is only a hand full of messages and Snapcast works by reading the common base header first, and continue with the specific message, this would have to be changed also.
BTW: the messages are already available in Pyhton: https://github.com/happyleavesaoc/python-snapcast
