### ISSUE TITLE
a short doc/CONTRIBUTING.md please

### ISSUE THREAD

**Issue by artmg** [badaix/snapcast#615]
To any snapcast developers,

I can be a bit slow sometimes, and get easily confused between different projects. The build instructions are clear, but I wonder if we could have a [doc/CONTRIBUTING.md](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) file to just mention which branch we should normally fork from, and any suggestions about best practice to PR. Regulars might think this is over-the-top, but just a couple of lines of guidance would help those like me who add to their forks infrequently.

Thanks, Art

**Comment by jorgenkraghjakobsen** [comment]
What about a meetup - We need something to get the planes up flying again. 
I would love to meet, share experience and discuss my development list. 
/Jakobsen

**Comment by artmg** [comment]
Hmmm, coming together is a good idea, but a meeting means everybody has to be synchronous. I only get available in bursts, so I wonder if there is an alternative medium for developers to share knowledge, ideas, roadmaps? In a way that supports Johannes as lead dev.

**Comment by badaix** [comment]
@artmg This issue is very justified, templates for contributing and issues are really missing. Also the readme needs an update (being less technical, but more what it is about, and why it's great ;)), and not to forget about the API documentation. All this would not only help the users but also me, because it will keep the number of issues low.
I will work on this. 
@jorgenkraghjakobsen we should actually really arrange a meetup, I'm curious and eager to hear from your development list. Regarding the planes: Snapcast is on cruise speed at the moment, I love to work on it, but my time is limited.

**Comment by badaix** [comment]
done: https://github.com/badaix/snapcast/blob/master/CONTRIBUTING.md
