### ISSUE TITLE
Fifo queue not flushing

### ISSUE THREAD

**Issue by toddhaugen** [badaix/snapcast#640]
OK so I have a snapcast server running buster 10 and a snapcast client running on HiFiBerry OS and a snapcast client running on the same device as the server.  I do not think the client matters here as both clients behave identical.  When I listen to audio over the line in, arecord -f dat > /tmp/snapfifo I find at some point the music flips back some amount of time, have not been able to isolate the amount of time, and replays the audio from the beginning of the session.  The second time through the queue is flushed.  Thoughts on how I can isolate the problem for replication?  It does happen every time I listen to the server just uncertain when it will jump back.  Not sure how to see where the content is coming from when it is streaming.  When I cat the /tmp/snapfifo during replay is shows a stream of digital content even through I am not piping anything into the queue.

**Comment by Kriegbaum** [comment]
So, using arecord to capture audio live and broadcast it, I ran into two issues and was able to fix both of them. In my setup, I was using systemd to launch an arecord routine as well as a snapserver, and as it happened, arecord always got to its routine first, creating the snapfifo as a file instead of a named pipe. Snapserver was still able to grab audio from it, but the data was just piling up until it expanded to the size of my SD card. My solution to that, since I didnt want to start monkeying around with systemd boot order, was to point snapserver to a location outside of /tmp and let it create the fifo, and launched arecord afterwards, now since the pipe doesnt get destroyed on reboot, there aren't any issues with that

The second issue is that arecord will, by default, cap out the size of an audio chunk it creates and then start a second file after either a certain amount of time or data used, cant remember which. Even if you are sending to a named pipe, it will create another file with a numbered suffix and start dumping data into that after some arbitrary limit is reached.

Hopefully that is helpful. If you continue to have issues and are interested, I can dig up exactly what my arecord settings are.

**Comment by badaix** [comment]
Thanks @Kriegbaum, no response by Todd => seems to be resolved
