### ISSUE TITLE
Snapclient won't start because: (Avahi) CACHE_EXHAUSTED

### ISSUE THREAD

**Issue by dflvunoooooo** [badaix/snapcast#647]
Hello everyone,
Thank you for your great work with snapcast. I am a great fan and have been using it for years now.
I had a problem with avahi and snapsever lately, since I set up a cups server, but luckily snapserver doesn't need avahi.

Today I was unable to start snapclient, because of the error: `[Info] (Avahi) (Browser) CACHE_EXHAUSTED`. 
I have no idea where this comes from. I set the avahi option `cache-entries-max=0` in `/etc/avahi/avahi-daemon.conf` and restarted the service, without effect. 
When i mask the avahi service snapclient wont't start with the error: `Exception: BrowseAvahi - Failed to create client: Daemon not running`.
I am totally at a loss. Is there a way to start snapclient without avahi? Or can anyone point me to a possible solution?

Thanks in advance.

**Comment by badaix** [comment]
You can use the `-h` or `--host` option to configure the server's IP address or host name

**Comment by dflvunoooooo** [comment]
Thank you for your fast answer. 
I usually use the `--host` option. It doesn't change anything.

**Comment by dflvunoooooo** [comment]
Is it possible to start snapclient without avahi? For example if I compile it?

**Comment by dflvunoooooo** [comment]
My mistake, I assumed the `--host` option was used, but I must have deleted it some time ago, sorry. With the  `--host` option snapclient starts successfully. 

But without it I still receive the same `(Avahi) CACHE_EXHAUSTED` error. I don't understand why.

**Comment by badaix** [comment]
On some of my systems it might take some seconds until the client get's the IP address from the Avahi service. It's implemented in Snapcast as in the Avahi client example: https://www.avahi.org/doxygen/html/client-browse-services_8c-example.html and has not been touched the last years, and never caused problems, in sense that the host has not eventually been resolved. If this problem is persistent on your system (I don't have such a system), you might try to debug and fix this issue (which I would highly appreciate), or use as workaround the `host` command line option.
I will close this ticket now, maybe you can experiment with the Avahi command line tools, like `avahi-browse` to check if the server is reported there.

**Comment by dflvunoooooo** [comment]
I did dig a bit. The problem seems to be an avahi problem. On my desktop with Arch Linux I can start snapclient only, wihout providing the `--host` option, by uncommenting the line `cache-entries-max=4096` in `/etc/avahi/avahi-daemon.conf`. Then I get the `[Info] (Avahi) (Browser) CACHE_EXHAUSTED` info once, and immediately there after snapclient shows `[Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'` and it is working as expected.  

The funny thing is, on my two Raspberry Pis with Arch Linux ARM, snapclient is working without the `--host` option and without editing the `avahi-daemon.conf`. 

A further sign towards avahi is, that `avahi-browse --all` is not showing anything if I do not uncomment the line in `avahi-daemon.conf`.

Thanks for your help, really love snapcast :)
