### ISSUE TITLE
Fedora (or RedHat/CentOS) RPM(s)?

### ISSUE THREAD

**Issue by derekatkins** [badaix/snapcast#649]
HI,

I see lots of distros on the list but nothing RPM-based?  Nothing for CentOS/RHEL and/or Fedora?
Google shows one or two COPR links, at least 2-3 years old (0.8)?

What would it take to "support" Fedora?

**Comment by badaix** [comment]
Somehow find some package maintainer at Fedora, who is interested to build official RPMs.

**Comment by derekatkins** [comment]
Are there even Specfiles to start from?

**Comment by badaix** [comment]
Looks quite straight forward to build RPM packages: https://www.thegeekstuff.com/2015/02/rpm-build-package-example/
Only thing that is missing are the `spec` files. 
If you build some, I would be happy to merge them into the project.

**Comment by badaix** [comment]
I will close this now, because Fedora packages are not in the scope of this project (no packages at all, debian is only there because I'm using it to distribute updates within my home network). 
Anyways, if you build spec files, I will be happy to merge your PR into the project. 
You can request getting new packages into Fedora: https://fedoraproject.org/wiki/Getting_a_Fedora_package_in_EPEL
