### ISSUE TITLE
Snapcast Stream from Python

### ISSUE THREAD

**Issue by NetherStar64** [badaix/snapcast#662]
Hey, so I'm currently working on a raspberry pi player, and I now want to add the functionality to output my audio to other devices. But my audio stream is an PCM Stream As a Byte, using decode() will result in an Error cause I'm decoding These Non-Existing Characters.  decode("UTF-8","ignore") results in a lot of Noise on my Client. I can't write the bytes directly to the Output, what to do?
![15948219011901246942406310949102](https://user-images.githubusercontent.com/63533734/87554892-03999b00-c6b5-11ea-96d7-ab3a81ac3dd4.jpg)

**Comment by uSpike** [comment]
Hi, this issue tracker is really meant for issues within `snapcast`, and not other projects.  There's a bunch of other forums and chats for learning python, such as https://reddit.com/r/learnpython and https://pythondiscord.com/

---

If you have a binary stream then `decode()` will try to decode it into a string.  In this case, that stream is not a string, it is PCM data, so `decode()` isn't what you want.

You need to open your `snapfifo` as a binary file so that you can write binary data to it, see https://docs.python.org/3/library/functions.html#open

Also, I'd recommend you post the code directly into the issue next time as text.

**Comment by NetherStar64** [comment]
Oh, I thank you so much. I'm actually sorry to steal your time in this Issue, I just couldn't get it working. Thank you ;-) ! Next time I'm gonna write somewhere different, but thanks a lot!
