### ISSUE TITLE
Have a way to configure backends to make the software more portable

### ISSUE THREAD

**Issue by ioangogo** [badaix/snapcast#71]
The reliance on ALSA with this program is limiting the use of it on other platforms, if there was a way to configure what outputs the sound it may aid the development of ports to windows and mac and may provide a way to allow snapcast to use the more cross-unix OSS sound system meaning that it will work better on the BSD's out of the box if they dont have alsa in base.

This is more of a feature request/suggestion than a issue

**Comment by badaix** [comment]
I know about the limitation, as Android already uses OpenSL, because ALSA is not really available here.
So at least the possibility to have different player classes is already there, but currently the choice is done by a compiler flag.
It's hard to use an arbitrary cross platform audio lib (actually I started with PortAudio), since Snapcast needs some predictable playout latency, so as ALSA, that can tell you when a sample will be passed to the DSP.

**Comment by badaix** [comment]
If there will be more than one backend for a platform, I will make it configurable
