### ISSUE TITLE
Can't build 0.23 without PulseAudio

### ISSUE THREAD

**Issue by duhow** [badaix/snapcast#773]
**Describe the bug**
When trying to build Snapcast client [v0.23.0](https://github.com/badaix/snapcast/tree/v0.23.0), having an error that PulseAudio was not found.
I don't want to use the PulseAudio backend, but also I can't find any way to disable build for that.
Using `make` command.
Also docs are a bit confusing regarding if I should best use CMake or just the Makefile for Linux.
No issues with previous version [v0.22.0](https://github.com/badaix/snapcast/tree/v0.22.0).

**Steps to Reproduce**
```
ADD_FLAGS="-I${PACKAGE_SRC_DIR} -I${STAGING_DIR}/${INSTALL_PREFIX}/${BUILD_TARGET}/include ${BUILD_CFLAGS} --sysroot=${STAGING_DIR}"

make -j${MAKE_JOBS} \
  CC="${BUILD_CC}" CXX="${BUILD_CXX}" \
  ADD_LDFLAGS="${BUILD_LDFLAGS}" ADD_CFLAGS="${ADD_FLAGS}" \
  PREFIX=${INSTALL_PREFIX} ARCH=arm
```

**Environment details**
- OS: Ubuntu 20.04 Docker, building with GCC 7.4.1 for `armhf`.
- Snapcast version 0.23.0
- Building from source

**Attach logfile if applicable**

```log
/xiaoai/build-packages/build/armv7/toolchain/bin/arm-linux-gnueabihf-g++ -O2 -I/xiaoai/build-packages/build/armv7/snapcast -I/xiaoai/build-packages/staging/armv7//usr/arm-linux-gnueabihf/include -I/xiaoai/build-packages/staging/armv7//usr/include -Os --sysroot=/xiaoai/build-packages/staging/armv7 -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.23.0\" -I. -I.. -I../common -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_PULSE -DHAS_AVAHI -DHAS_DAEMON -c snapclient.cpp -o snapclient.o
In file included from snapclient.cpp:33:0:
player/pulse_player.hpp:27:10: fatal error: pulse/pulseaudio.h: No such file or directory
 #include <pulse/pulseaudio.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:123: snapclient.o] Error 1
make[1]: Leaving directory '/xiaoai/build-packages/build/armv7/snapcast/client'
```

**Comment by duhow** [comment]
Had to do a patch to disable the client Makefile.

```diff
--- a/client/Makefile
+++ b/client/Makefile
@@ -84,9 +84,9 @@
 else
 
 CXX       = g++
-CXXFLAGS += -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_PULSE -DHAS_AVAHI -DHAS_DAEMON
-LDFLAGS  += -lrt -lasound -lpulse -lvorbis -lavahi-client -lavahi-common -latomic
-OBJ      += ../common/daemon.o player/alsa_player.o player/pulse_player.o browseZeroConf/browse_avahi.o
+CXXFLAGS += -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON
+LDFLAGS  += -lrt -lasound -lvorbis -lavahi-client -lavahi-common -latomic
+OBJ      += ../common/daemon.o player/alsa_player.o browseZeroConf/browse_avahi.o
 
 endif
```

**Comment by kingosticks** [comment]
> Snapclient v0.23 will depend on PulseAudio (libpulse), which introduces these indirect dependencies. You can build Snapclient on a machine without pulseaudio or disable it explicitly during compile time with [-DBUILD_WITH_PULSE=OFF](https://github.com/badaix/snapcast/blob/1f98c790734f7b5de01497fa5243149dddd6dc0b/CMakeLists.txt#L62).

**Comment by duhow** [comment]
Right, but that's with CMake or just with Makefile would also work?

**Comment by badaix** [comment]
Please use cmake. The makefiles are deprecated and will be removed soon.

**Comment by duhow** [comment]
Thanks for the confirmation!

**Comment by badaix** [comment]
The makefiles will build everything, they don't support flags to disable certain features. What's currently missing for CMake is a proper `install` target. It will only copy some files, but it will not create the snapclient user, nor will it setup Snapclient as systemd service.

**Comment by Saiyato** [comment]
Sorry to barge into this convo, I ran into this problem as well last night. I was rebuilding my containers, because there was a new vulnerability (in libssl). It was the first build in two months, so it's the first one with the pulse dependency.

I'm not too knowledgeable on compiling, apart from lazy C# using Visual Studio :wink: What I understand is that make uses the Makefile(s) and cmake is more of a build generator (e.g. building ninja or make files). So in some abstraction I know what this means; I would use cmake to generate the files/instructions I need to build.

Now my problem, as I'm only partially knowing what I'm doing. If I build using cmake I get different binaries than when building using the Makefiles. This makes sense, as I probably just need to align the parameters. Can you give me a hint or point me to files to read/interpret as to what arguments you (would) pass with cmake to build the client without Pulse? I'm happy to learn, but to be honest, I don't know where to start

I used the following: `cmake -DBUILD_WITH_PULSE=OFF -DBUILD_SERVER=OFF -DCMAKE_BUILD_TYPE=Release -B build .`
At this point I'm not sure if the `-W` arguments (no-deprecated & no-unused-typedef) are necessary. I'm also unsure if I should provide more (explicit) arguments to cmake for this particular purpose.

Note that I'm building on Alpine for the smallest possible footprint in terms of containers. So building without pulse takes preference, as Pulse takes up ~25MB; I'm happy to provide the option additionally though.

I know that I'm probably not asking all the right questions, but I'd like to understand how it works 😄

**Comment by badaix** [comment]
You can see how cmake invokes make by calling `make VERBOSE=1`:

```shell
johannes@Laptop:~/Develop/snapcast$ cmake -S . -B build -DBOOST_ROOT=/home/johannes/Develop/boost_1_75_0 -DCMAKE_BUILD_TYPE=Release 

johannes@Laptop:~/Develop/snapcast/build$ make VERBOSE=1
...
[  1%] Building CXX object common/CMakeFiles/common.dir/resampler.cpp.o
cd /home/johannes/Develop/snapcast/build/common && /usr/bin/c++  -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -DHAS_EXPAT -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_PULSE -DHAS_SOXR -DHAS_TREMOR -DHAS_VORBIS -DHAS_VORBIS_ENC -DVERSION=\"0.24.0\" -I/home/johannes/Develop/snapcast -I/home/johannes/Develop/snapcast/include  -O3 -DNDEBUG   -Wall -Wextra -pedantic -Wno-unused-function -std=gnu++14 -o CMakeFiles/common.dir/resampler.cpp.o -c /home/johannes/Develop/snapcast/common/resampler.cpp
```

The -W options are hard coded in the `CMakeLists.txt`:
```
    add_compile_options(-Wall -Wextra -pedantic -Wno-unused-function)
```


This is quite similar to what the Makefiles do:

```shell
johannes@Laptop:~/Develop/snapcast$ ADD_CFLAGS="-I/home/johannes/Develop/boost_1_75_0" make -j 10
...
g++ -O2 -I/home/johannes/Develop/boost_1_75_0 -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -DHAS_ALSA -pthread -c snapserver.cpp -o snapserver.o

```

The biggest difference should be the lower optimization level in the Makefile (`-O2` vs `-O3`)


You can also see how the [nightlies](https://github.com/badaix/snapcast/actions) are [built](https://github.com/badaix/snapcast/tree/master/.github/workflows) (which are also be used for the [releases](https://github.com/badaix/snapcast/releases)).

The debian helper tools seem to inject some extra hardening options, e.g. [here](https://github.com/badaix/snapcast/runs/1947322935?check_suite_focus=true):

```
[  1%] Building CXX object common/CMakeFiles/common.dir/resampler.cpp.o
cd /home/runner/work/snapcast/snapcast/obj-x86_64-linux-gnu/common && ccache /usr/bin/c++ -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -DHAS_EXPAT -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DHAS_VORBIS -DHAS_VORBIS_ENC -DREVISION=\"7eff45fda7cadea9a5ce8829340d78da61da233d\" -DVERSION=\"0.24.0\" -I/home/runner/work/snapcast/snapcast -I/home/runner/work/snapcast/snapcast/include -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -pedantic -Wno-unused-function -std=gnu++14 -o CMakeFiles/common.dir/resampler.cpp.o -c /home/runner/work/snapcast/snapcast/common/resampler.cpp
```

namely these ones:

```
-fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
```

`-Wdata-time` will warn about DATE macros in the code, that will prevent reproducible builds.

You can pass additional arguments with `cmake ... -DCMAKE_CXX_FLAGS="$CXXFLAGS -<my option> -<another options>"`, as done in [self-hosted.yml](https://github.com/badaix/snapcast/blob/master/.github/workflows/self-hosted.yml): `-DCMAKE_CXX_FLAGS="$CXXFLAGS -Wno-psabi"`

**Comment by Saiyato** [comment]
Hi all,

I've been working on this, and did a new throw at this today. I still don't really get everything, I understand I should use cmake and that it takes arguments. For now that's enough I suppose :smile: I came up with the following build script (excludes PulseAudio) for the client:
```
# Install SnapClient on minimal OS
FROM amd64/alpine:latest

MAINTAINER Saiyato

RUN apk -U add alsa-lib-dev avahi-dev bash build-base ccache cmake expat-dev flac-dev git libvorbis-dev opus-dev soxr-dev  \
 && cd /root \
 && git clone --recursive https://github.com/badaix/snapcast.git \
 && cd snapcast \
 && wget https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 && tar -xvjf boost_1_75_0.tar.bz2 \
 && cmake -S . -B build -DBOOST_ROOT=boost_1_75_0 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_WITH_PULSE=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SERVER=OFF .. \
 && cmake --build build --parallel 3 \
 && cp bin/snapclient /usr/local/bin \
 && apk --purge del alsa-lib-dev avahi-dev bash build-base ccache cmake expat-dev flac-dev git libvorbis-dev opus-dev soxr-dev \
 && apk add alsa-lib avahi-libs expat flac libvorbis opus soxr \
 && rm -rf /etc/ssl /var/cache/apk/* /lib/apk/db/* /root/snapcast

ENTRYPOINT ["snapclient"]
```

I added ccache, because I think it will help in building with parallelization, but I'm not entirely sure it's beneficial. Also boost should help, but all my previous builds were done without boost, so I'm not sure what it adds (faster compilation? asio dependencies?).

Since I'm building on Alpine (for footprint reasons), I'm missing some packages:
- libasound2-dev
- libvorbisidec-dev (for tremor; maybe not necessary?)
- avahi-daemon

And I explicitly omitted debhelper (and I would need to look for the Alpine equivalent), since I'm not going to create packages, but rather a Docker image. The size of the image is about 20megs (18,5 if you're feeling pedantic), which makes it perfect for SBC's.

If you see anything I did wrong or concluded wrong, feel free to correct me :wink: These are the times I learn the most.
Also thanks for all the help so far!
