### ISSUE TITLE
No sound on Android

### ISSUE THREAD

**Issue by jtrees** [badaix/snapcast#795]
**Describe the bug**
Using the Android app doesn't produce any sound.

**Steps to Reproduce**
1. Set up a Snapserver
2. Download Snapcast on a phone via F-Droid
3. Start playing music
4. Confirm everything is working with a PC client
5. Start Snapcast on the phone
6. Connect, press play
7. Ensure the phone volume is up

**Environment details**
- OS: /e/ 0.13 (based on Android 8.1.0)
- Snapcast version 0.7.0
- F-Droid version

**Additional details**
Using snapweb (and checking the server logs) confirms that the client is able to connect. Pressing play and stop has an effect. I get no sound though...

**Comment by badaix** [comment]
Please report this bug to the fdroid maintainer of Snapdroid, but don't expect the five years old 0.7 to work with a recent server version.
You can download a recent apk from the Snapdroid releases page or in the Google play store.

**Comment by xabolcs** [comment]
@jtrees , add IzzySoft's repo to your F-Droid installation!

```
https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A
```

For more information check the related F-Droid issue in Snapdroid's own page:
https://github.com/badaix/snapdroid/issues/2

**Comment by badaix** [comment]
Nice, I wasn't aware of this repo (or that one can add repos to FDroid). Though it doesn't sync for me `Error getting F-Droid index file => no mirrors available`.
Anyways: I don't know how Snapcast made it into the official F-Droid repo, I only heard/read back then that it will not be updated because of the strange and complicated build process. Years later, the Android toolchain got some features to streamline the build process (Snapclient is running as cross compiled binary within the App, and this cross compilation is now done in a single build step (used to be done manually before), but it still uses some manually compiled libs, which I've automated yesterday https://github.com/badaix/snapcast-deps, so I might make a PR to F-Droid soon to have it up to date).

**Comment by xabolcs** [comment]
> or that one can add repos to FDroid

I found out based on @IzzySoft's work in badaix/snapdroid#2 :) 
It is at: F-Droid settings /  (My Apps) Repositories /  + New Reposiory

I didn't know about it earlier, too.

For the F-Droid repo, I just followed IzzySoft's profile: https://android.izzysoft.de/repo/info

**Comment by jtrees** [comment]
> Please report this bug to the fdroid maintainer of Snapdroid, but don't expect the five years old 0.7 to work with a recent server version.
> You can download a recent apk from the Snapdroid releases page or in the Google play store.

Oh yeah. I didn't realise it wasn't up-to-date. Works with the newest version. Thanks!
