### ISSUE TITLE
Adding Metadata -- prefered method?

### ISSUE THREAD

**Issue by ashthespy** [badaix/snapcast#803]
I noticed that there is some rudimentary "metadata" implemented already for the `librespot` by reading off the stderr output.
https://github.com/badaix/snapcast/blob/1f98c790734f7b5de01497fa5243149dddd6dc0b/server/streamreader/librespot_stream.cpp#L138-L145

I have wrapped `librespot` to create a pipe with proper metadata and would like to incorporate some metadata support into snapcast for Spotify. 

From a quick  look at the codebase, this can be done similar to how the [`shairport-sync`](https://github.com/badaix/snapcast/blob/master/server/streamreader/airplay_stream.cpp) metadata stream is read, but then would require patching the `librespot_stream.cpp` with yet another "custom" implementation. 

As I am not very well versed with this codebase, I would like to ask if is there already a `stream` agnostic way to add metadata to a particular stream?
I could then plug my `librespot` based daemon to output to this preferred stream as well, and then configure the server to read the audio stream + metadata stream.

**Comment by badaix** [comment]
There is no generic way to add meta tags. I've started with it in the `metatags` branch, but focused on reading meta data from MPD and cover art from musicbrainz, not yet on the framework part. 
I'm somehow bombed by support and feature requests, eating up my rare spare time that I can invest into Snapcast, no time for the fun stuff :(

**Comment by ashthespy** [comment]
Ah, maybe I could pick your brain about how you see metadata support evolving? 
I am not sure you'd be happy to add yet another stream reader for Spotify again, so was wondering if there way another way. 
For example, I currently expose metadata over a udp socket in JSON format. 
```rust
let json = json!(
    { "metadata" : {
        "track_id": spotify_id.to_base62(),
        "track_name": track.name,
        "artist_id": artist_ids,
        "artist_name": artist_names,
        "album_id": album.id.to_base62(),
        "album_name": album.name,
        "duration_ms": track.duration,
        "albumartId": covers,
        "position_ms": position_ms.unwrap_or(0),
    }});            
```



> I'm somehow bombed by support and feature requests, eating up my rare spare time that I can invest into Snapcast, no time for the fun stuff :(

Take care! :-)

**Comment by Sirnut** [comment]
@ashthespy Could I get some more details on how you're sharing metadata between your server and clients? I'm trying to brainstorm a way to get the data out to multiple volumio clients. What I envision is probably a dirty way to go about it, but since I only use spotify connect to play music back I want to package the data on the server where the spotify connect plugin is located, send it to the clients (who's only installed plugin is a snapclient) to have it then broadcast to the UI

**Comment by ashthespy** [comment]
Ah, I was hoping that you had some plans for a stream agnostic way of incorporating metadata, instead of a custom metadata parser for each stream. 


> Instead the official metadata should be used, which currently not really available, only in the debug logs and when using the --onevent script, which lacks important information, such as artist and album and this script method is also not very handy to integrate.

W.t.r to `libresepot` we keep having discussions about [metadata](https://github.com/librespot-org/librespot/issues/7), but ultimately we arrive at the concussion that `librespot` is a library, and the current `librespot` binary should get moved into [`librespotd`](https://github.com/librespot-org/librespotd) that handles metadata in a plugable manner similar to how backends are currently implemented. 

But this still leaves a few thoughts from my side on the preferred method to get metadata in

-- We could patch it to add more information in a parseable manner to stdout, (Additional metadata is currently lacking as this is done from the player thread that is nonblocking, but this is an implementation detail that isn't of much interest to you ;-))
-- Would it work to have a separate pipe for just metadata? 
-- Is there a standard metadata from [that is preferred? ;-)](https://xkcd.com/927/)

**Comment by kingosticks** [comment]
Can we use Snapsever's [`Stream.SetMeta` JSON-RPC method](https://github.com/badaix/snapcast/blob/master/server/server.cpp#L409) for setting the metadata? In the case of Mopidy we could easily have an extension to do that. Or some external glue script/program doing it using MPD, which has the bonus of providing support for both Mopidy and mpd streams.The metatags branch seemed to be going in the other direction and implementing a "custom metadata parser for each stream" approach, is that preferable?

Relatedly, I noticed `Stream.OnMetadata` and `Stream.SetMeta` are missing from the [RPC API doc](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md). Would a PR to add those be helpful?

**Comment by badaix** [comment]
damn, i see. I was already wondering why mpDris2 emphasizes that it's running in the user session.

**Comment by badaix** [comment]
Update on this: I've started to add generic meta data and stream control support. There is an early version of the [documentation in the develop branch](https://github.com/badaix/snapcast/blob/develop/doc/json_rpc_api/stream_plugin.md)

In a nutshell: 
A stream can be configure to start a control script, using the new parameter `controlscript`:

```
source = pipe:///tmp/snapfifo?name=Pipe&codec=flac&controlscript=/home/johannes/Develop/snapcast/control/meta_mpd.py -d
```

The server will send [JSON RPC commands](https://github.com/badaix/snapcast/blob/develop/doc/json_rpc_api/stream_plugin.md) to the script's stdin and receive responses and notification from it's stdout.
In future a plugin might also be a shared library, configured with `controlplugin` or something.

Commands are for instance `play`, `pause`, `stop`, `getMetadata`,  `setProperty [shuffle, loop, ..]` and notifications are used to push metadata and property changes to the Snapserver.
The interface is heavily inspired by [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/index.html), which is serving exactly the same purpose.

Metadata, properties and control commands are exposed to Snapserver's RPC interface, so that clients can get the metadata and control specific streams via the Snapserver's websocket interface. 

This is still work in progress and changes almost every day, but the interface is starting to get "stable". As proof of concept I'm developing a control script for MPD, based on [mpDris2](https://github.com/eonpatapon/mpDris2) and a [Snapcast to MPRIS script](https://github.com/badaix/snapcast/blob/develop/control/snapcast_mpris.py) for the desktop as well as on an integration into [Snapweb](https://github.com/badaix/snapweb/), maybe also in [Snapdroid](https://github.com/badaix/snapdroid).

As a teaser: this is how it looks like at the moment:

![image](https://user-images.githubusercontent.com/10322999/122432505-aa597c00-cf95-11eb-9b0c-f5f64dccaeb5.png)
