### ISSUE TITLE
add multicast support

### ISSUE THREAD

**Issue by treaki** [badaix/snapcast#90]
Not that much important as pulseaudio but it would be nice if you have a lot of clients that the transfer would be done using multicast to save network bandwidth.

thanks

**Comment by badaix** [comment]
Hi,

I was thinking about multicast (it seems to be tailor made for snapcast), but when taking a closer look, it seems that there are a couple of drawbacks with multicast over WiFi, as described in this [paper](https://tools.ietf.org/id/draft-mcbride-mboned-wifi-mcast-problem-statement-00.html):

> Multicast over wifi has been used to low levels of success, usually to a point of being so negative that multicast over wifi is not allowed ... [snip] ... To make make multicast over wifi work successfully they often need to modify the multicast to instead be sent as unicast in order for it to successfully transmit with useable quality ...

and posted on [superuser.com](http://superuser.com/questions/730288/why-do-some-wifi-routers-block-multicast-packets-going-from-wired-to-wireless):

> Why do some WiFi routers block multicast packets going from wired to wireless?
It's usually due to bugs in the Wi-Fi home gateway routers (APs), or sometimes in the wireless client chipsets/drivers/software...

or [here](http://superuser.com/questions/695813/wifi-udp-unicast-vs-multicast-speed):

> WiFi UDP unicast vs. multicast speed
Any kind of multicast/broadcast over Wi-Fi is going to be slow because Wi-Fi requires multicasts and broadcasts to be sent at a kind of "lowest common denominator" transmission speed...

When streaming CD quality audio, you will need 1.4 Mbit/s per connected client. Because Snapcast is using FLAC, it's roughly 0.8 Mbit/s per client. In a typical home setup you might connect three or four (3.2 Mbit) or maybe at most up to ten (8 Mbit) clients, which can be easily handled by (wireless-) LANs.
Because of the unicast TCP transfer, it is also guaranteed that there are no packet losses or out of order packets that would result in degraded audio quality or require a TCP like protocol on top.

**Comment by treaki** [comment]
i am having 4 snapclients, 1 of them are connected through ethernet with on the same broadcastdomain one is on the onto another through a router that supports multicast (and is truced trough vlan to my switch in the living room) on which is a wifi network and an wired connected client and the last one is done using if lo. So for me multicast would help because only 1 / 4 clients are using wifi so it would be no problem if that would fallback to unicast but still would only output two streams of the eth interface of my snapserver box, one that fits to multcast ethernet and another for that dumb wifi. I tryed once to stack up to 6 ethernet connected clients and have got problems on that eth (not on the router not on the switches not anywhere else but if it had multicast support it would be much better.

so please keep that on your roadmap

thanks in advance

**Comment by ondonadas** [comment]
(Hi guys) Not a general solution, perhaps It would be nice if Snapchat server runs inside OpenWRT machine, and same machine brings AP features to your home. In such way you can control Multicast, because OpenWRT can deal with Multicast without issues. Same for the clients.

Looking for keep Multicast in the roadmap

Thanks
