### ISSUE TITLE
Mopidy and snapcast

### ISSUE THREAD

**Issue by MTRNord** [badaix/snapcast#94]
How can I output normaly to the web Overlays of Mopidy and also to snapcast at the same time? Is there any Documentation?

**Comment by pfink** [comment]
What do you mean with "output normaly to the web Overlays of Mopidy"?

**Comment by MTRNord** [comment]
Ah sorry I meant how I am able to get output to the local device where it runs ans snapcast (I first thaugt that the sound came trough the browser because I ran it in an Vbox on the same device).

In detail I want to have sound Local on the device where Mopidy runs and sound output to snapcast.

**Comment by pfink** [comment]
As I already wrote within another thread: This doesn't make so much sense because you'll loose synchronicity if you do that. If you don't have the requirement to play audio **synchronous**, you should not use snapcast. In this case, you can use any software that supports audio streaming (e.g. pulseaudio or mpd) and it'll probably work much better than snapcast.

If you do have the requirement of synchronous audio playback, you should use a snapclient locally.

**Comment by MTRNord** [comment]
ok thanks for info

**Comment by badaix** [comment]
you can feed the Mopidy output in the Snapserver only, i.e. not play it into Snapserver's fifo *and* to the sound card, but only into the fifo.
On the same device you can install the Snapclient, which will do the actual audio playback.
=> audio is played only through Snapclients, even on the server => the audio will be synchronous.
Only drawback is the latency of (default) 1000ms
